import { Meta } from '@storybook/react';
import { Text } from './Text';
import { NTypography } from '../models';
declare const _default: Meta<typeof Text>;
export default _default;
export declare const DefaultText: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NTypography.TTextProps>;
export declare const CodeText: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NTypography.TTextProps>;
export declare const KeyboardText: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NTypography.TTextProps>;
export declare const MarkText: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NTypography.TTextProps>;
export declare const DeleteText: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NTypography.TTextProps>;
