import { DataTypeWithTag, GroupedDataType, MultipleSorterDataType, SpanDataType } from '../models';
import { Story } from '../Table.stories';
export declare const DefaultTable: Story<DataTypeWithTag>;
export declare const SelectionTable: Story;
export declare const FilterSorterTable: Story;
export declare const FilterInTreeTable: Story;
export declare const FilterSearchTable: Story;
export declare const MultipleSorterTable: Story<MultipleSorterDataType>;
export declare const BorderTitleFooterTable: Story;
export declare const SpanTable: Story<SpanDataType>;
export declare const FixedHeaderTable: Story;
export declare const FixedColumnsTable: Story;
export declare const FixedColumnsAndHeaderTable: Story;
export declare const GroupedColumnsTable: Story<GroupedDataType>;
export declare const EllipsisColumnTable: Story;
export declare const EllipsisWithTooltipTable: Story;
export declare const ResponsiveColumnsTable: Story;
export declare const CustomEmptyTable: Story<DataTypeWithTag>;
