import { Meta } from '@storybook/react';
import { NBreadcrumb } from '../../..';
declare const meta: Meta<NBreadcrumb.TProps>;
export default meta;
export declare const Default: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NBreadcrumb.TProps<import('../../..').AnyObject>>;
export declare const WithIcon: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NBreadcrumb.TProps<import('../../..').AnyObject>>;
export declare const Separator: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NBreadcrumb.TProps<import('../../..').AnyObject>>;
export declare const WithMenu: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NBreadcrumb.TProps<import('../../..').AnyObject>>;
export declare const IndependentSeparator: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NBreadcrumb.TProps<import('../../..').AnyObject>>;
export declare const LastCrumbTitle: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NBreadcrumb.TProps<import('../../..').AnyObject>>;
