import { Meta } from '@storybook/react';
import { NMenu } from '../models';
declare const meta: Meta<NMenu.TProps>;
export default meta;
export declare const Default: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NMenu.TProps>;
export declare const TopNavigation: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NMenu.TProps>;
export declare const InlineMenu: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NMenu.TProps>;
export declare const VerticalMenu: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NMenu.TProps>;
export declare const CollapsedInlineMenu: () => import("react/jsx-runtime").JSX.Element;
export declare const OpenCurrentSubMenu: () => import("react/jsx-runtime").JSX.Element;
export declare const ThemesMenu: () => import("react/jsx-runtime").JSX.Element;
export declare const SwitchMenuTheme: () => import("react/jsx-runtime").JSX.Element;
