import { Meta } from '@storybook/react';
import { Filter } from '../Filter';
import { NFilter } from '../models';
declare const _default: Meta<typeof Filter>;
export default _default;
export declare const DefaultFilter: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NFilter.TProps>;
export declare const OverflowFilter: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NFilter.TProps>;
export declare const LongFilterLabel: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NFilter.TProps>;
export declare const FilterLabelWithClick: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NFilter.TProps>;
export declare const FilterPanel: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NFilter.TProps>;
