import { Meta } from '@storybook/react';
import { NRangePicker } from '../../range-picker';
declare const meta: Meta<NRangePicker.TProps>;
export default meta;
export declare const Default: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NRangePicker.TProps>;
export declare const WithOpen: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NRangePicker.TProps>;
export declare const WithDisabled: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NRangePicker.TProps>;
export declare const WithReadonly: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NRangePicker.TProps>;
export declare const WithAutoFocus: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NRangePicker.TProps>;
export declare const WithMinDate: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NRangePicker.TProps>;
export declare const WithMaxDate: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NRangePicker.TProps>;
export declare const WithCustomFormatMask: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NRangePicker.TProps>;
export declare const WithTimeAndSeparator: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NRangePicker.TProps>;
export declare const WithMode: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NRangePicker.TProps>;
export declare const WithTimeAndMaskMode: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NRangePicker.TProps>;
