declare const _default: {
  "$schema": "../../../theme.schema.json",
  "algorithm": "light",
  "id": "axenix-ui-default-theme",
  "token": {
    "scrollThumbColor": "rgba(0, 0, 0, 0.2)",
    "scrollThumbColorHover": "rgba(0, 0, 0, 0.3)",
    "scrollThumbColorActive": "rgba(0, 0, 0, 0.4)",
    "scrollThumbPadding": 2,
    "orange": "#F37022",
    "borderRadius": 6,
    "borderRadiusLG": 8,
    "borderRadiusSM": 4,
    "borderRadiusXS": 2,
    "colorBgBase": "#ffffff",
    "colorBgContainer": "#ffffff",
    "colorBgContainerDisabled": "#ffffff",
    "colorBgElevated": "#ffffff",
    "colorBgLayout": "#ffffff",
    "colorBgMask": "rgba(0, 0, 0, 0.45)",
    "colorBgSpotlight": "rgba(0, 0, 0, 0.85)",
    "colorBgTextActive": "rgba(0, 0, 0, 0.15)",
    "colorBgTextHover": "rgba(0, 0, 0, 0.06)",
    "colorBorder": "#d9d9d9",
    "colorBorderBg": "#ffffff",
    "colorBorderSecondary": "#f0f0f0",
    "colorError": "#ff4d4f",
    "colorErrorActive": "#d9363e",
    "colorErrorBg": "#fff2f0",
    "colorErrorBgHover": "#fff1f0",
    "colorErrorBorder": "#ffccc7",
    "colorErrorBorderHover": "#ffa39e",
    "colorErrorHover": "#ff7875",
    "colorErrorOutline": "rgba(255, 38, 6, 0.06)",
    "colorErrorText": "#ff4d4f",
    "colorErrorTextActive": "#d9363e",
    "colorErrorTextHover": "#ff7875",
    "colorFill": "rgba(0, 0, 0, 0.15)",
    "colorFillAlter": "rgba(0, 0, 0, 0.02)",
    "colorFillAlterSolid": "#fafafa",
    "colorFillContent": "rgba(0, 0, 0, 0.06)",
    "colorFillContentHover": "rgba(0, 0, 0, 0.15)",
    "colorFillQuaternary": "rgba(0, 0, 0, 0.02)",
    "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
    "colorFillTertiary": "rgba(0, 0, 0, 0.04)",
    "colorIcon": "rgba(0, 0, 0, 0.65)",
    "colorIconDisabled": "rgba(0, 0, 0, 0.25)",
    "colorIconHover": "rgba(0, 0, 0, 0.88)",
    "colorInfo": "#f37022",
    "colorInfoActive": "#cc5012",
    "colorInfoBg": "#fff8f0",
    "colorInfoBgHover": "#ffe3c7",
    "colorInfoBorder": "#ffcb9e",
    "colorInfoBorderHover": "#ffb175",
    "colorInfoHover": "#ff944d",
    "colorInfoText": "#f37022",
    "colorInfoTextActive": "#cc5012",
    "colorInfoTextHover": "#ff944d",
    "colorLink": "#f37022",
    "colorLinkActive": "#cc5012",
    "colorLinkHover": "#ff944d",
    "colorPrimary": "#f37022",
    "colorPrimaryActive": "#cc5012",
    "colorPrimaryBg": "#fff8f0",
    "colorPrimaryBgHover": "#ffe3c7",
    "colorPrimaryBorder": "#ffcb9e",
    "colorPrimaryBorderHover": "#ffb175",
    "colorPrimaryHover": "#ff944d",
    "colorPrimaryText": "#f37022",
    "colorPrimaryTextActive": "#cc5012",
    "colorPrimaryTextHover": "#ff944d",
    "colorSplit": "rgba(0, 0, 0, 0.06)",
    "colorSuccess": "#52c41a",
    "colorSuccessActive": "#389e0d",
    "colorSuccessBg": "#f6ffed",
    "colorSuccessBgHover": "#d9f7be",
    "colorSuccessBorder": "#b7eb8f",
    "colorSuccessBorderHover": "#95de64",
    "colorSuccessHover": "#95de64",
    "colorSuccessText": "#52c41a",
    "colorSuccessTextActive": "#389e0d",
    "colorSuccessTextHover": "#73d13d",
    "colorText": "rgba(0, 0, 0, 0.88)",
    "colorTextBase": "#000000",
    "colorTextDescription": "rgba(0, 0, 0, 0.45)",
    "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
    "colorTextHeading": "rgba(0, 0, 0, 0.88)",
    "colorTextLabel": "rgba(0, 0, 0, 0.65)",
    "colorTextLightSolid": "#ffffff",
    "colorTextPlaceholder": "rgba(0, 0, 0, 0.45)",
    "colorTextQuaternary": "rgba(0, 0, 0, 0.25)",
    "colorTextSecondary": "rgba(0, 0, 0, 0.65)",
    "colorTextTertiary": "rgba(0, 0, 0, 0.45)",
    "colorWarning": "#faad14",
    "colorWarningActive": "#d48806",
    "colorWarningBg": "#fffbe6",
    "colorWarningBgHover": "#fff1b8",
    "colorWarningBorder": "#ffe58f",
    "colorWarningBorderHover": "#ffd666",
    "colorWarningHover": "#ffd666",
    "colorWarningOutline": "rgba(255, 215, 5, 0.1)",
    "colorWarningText": "#faad14",
    "colorWarningTextActive": "#d48806",
    "colorWarningTextHover": "#ffc53d",
    "colorWhite": "#ffffff",
    "controlHeight": 32,
    "controlHeightLG": 40,
    "controlHeightSM": 24,
    "controlHeightXS": 16,
    "controlInteractiveSize": 16,
    "controlItemBgActive": "#fff8f0",
    "controlItemBgActiveDisabled": "rgba(0, 0, 0, 0.15)",
    "controlItemBgActiveHover": "#ffe3c7",
    "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
    "controlOutline": "rgba(243, 112, 34, 0.1)",
    "controlOutlineWidth": 2,
    "controlPaddingHorizontal": 12,
    "controlPaddingHorizontalSM": 8,
    "controlTmpOutline": "rgba(0, 0, 0, 0.02)",
    "fontFamily": "Inter",
    "fontFamilyCode": "Courier Prime",
    "fontSize": 14,
    "fontSizeHeading1": 38,
    "fontSizeHeading2": 30,
    "fontSizeHeading3": 24,
    "fontSizeHeading4": 20,
    "fontSizeHeading5": 16,
    "fontSizeIcon": 12,
    "fontSizeLG": 16,
    "fontSizeSM": 12,
    "fontSizeXL": 20,
    "fontWeightNormal": "400",
    "fontWeightStrong": 600,
    "lineHeight": 1.5714285714285714,
    "lineHeightHeading5": 1.5,
    "lineHeightHeading4": 1.4,
    "lineHeightHeading3": 1.3333333333333333,
    "lineHeightHeading2": 1.2666666666666666,
    "lineHeightHeading1": 1.2105263157894737,
    "lineHeightLG": 1.5,
    "lineHeightSM": 20,
    "lineWidth": 1,
    "lineWidthBold": 2,
    "lineWidthFocus": 4,
    "margin": 16,
    "marginLG": 24,
    "marginMD": 20,
    "marginSM": 12,
    "marginXL": 32,
    "marginXS": 8,
    "marginXXL": 48,
    "marginXXS": 4,
    "padding": 16,
    "paddingContentHorizontal": 16,
    "paddingContentHorizontalLG": 24,
    "paddingContentHorizontalSM": 16,
    "paddingContentVertical": 12,
    "paddingContentVerticalLG": 16,
    "paddingContentVerticalSM": 8,
    "paddingLG": 24,
    "paddingMD": 20,
    "paddingSM": 12,
    "paddingXL": 32,
    "paddingXS": 8,
    "paddingXXS": 4,
    "screenLG": 992,
    "screenLGMax": 1199,
    "screenLGMin": 992,
    "screenMD": 768,
    "screenMDMax": 991,
    "screenMDMin": 768,
    "screenSM": 576,
    "screenSMMax": 767,
    "screenSMMin": 576,
    "screenXL": 1200,
    "screenXLMax": 1599,
    "screenXLMin": 1200,
    "screenXS": 480,
    "screenXSMax": 575,
    "screenXSMin": 480,
    "screenXXL": 1600,
    "screenXXLMin": 1600,
    "size": 16,
    "sizeLG": 24,
    "sizeMD": 20,
    "sizeMS": 16,
    "sizePopupArrow": 16,
    "sizeSM": 12,
    "sizeStep": 4,
    "sizeUnit": 4,
    "sizeXL": 32,
    "sizeXS": 8,
    "sizeXXL": 48,
    "sizeXXS": 4,
    "tableMinWidth": 1,
    "transparent": "rgba(0, 0, 0, 0)"
  },
  "components": {
    "Input": {
      "paddingInlineSM": 7,
      "paddingInlineLG": 11,
      "paddingInline": 11,
      "paddingBlockSM": 0,
      "paddingBlockLG": 7,
      "paddingBlock": 4,
      "paddingXXS": 4,
      "paddingXS": 8,
      "paddingSM": 12,
      "paddingLG": 24,
      "lineWidth": 1,
      "lineHeightLG": 1.4,
      "lineHeight": 1.5714285714285714,
      "fontSizeLG": 16,
      "fontSizeIcon": 12,
      "fontSize": 14,
      "controlPaddingHorizontalSM": 8,
      "controlPaddingHorizontal": 12,
      "controlOutlineWidth": 2,
      "controlOutline": "rgba(243, 112, 34, 0.1)",
      "controlHeightSM": 24,
      "controlHeightLG": 40,
      "controlHeight": 32,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "borderRadius": 6,
      "colorWarningOutline": "rgba(255, 215, 5, 0.1)",
      "colorWarningBorderHover": "#ffd666",
      "colorWarning": "#faad14",
      "colorTextTertiary": "rgba(0, 0, 0, 0.45)",
      "colorTextQuaternary": "rgba(0, 0, 0, 0.25)",
      "colorTextPlaceholder": "rgba(0, 0, 0, 0.25)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimary": "#f37022",
      "colorIconHover": "rgba(0, 0, 0, 0.88)",
      "colorIcon": "rgba(0, 0, 0, 0.45)",
      "colorFillAlter": "rgba(0, 0, 0, 0.02)",
      "colorErrorOutline": "rgba(255, 38, 6, 0.06)",
      "colorErrorBorderHover": "#ffa39e",
      "colorError": "#ff4d4f",
      "colorBorder": "#d9d9d9",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "colorBgContainer": "#ffffff",
      "hoverBorderColor": "#ff944d",
      "addonBg": "rgba(0, 0, 0, 0.02)",
      "activeBorderColor": "#f37022",
      "colorFillTertiary": "rgba(0, 0, 0, 0.04)",
      "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
      "colorErrorBgHover": "#fff1f0",
      "colorErrorBg": "#fff2f0",
      "colorWarningBg": "#fffbe6",
      "colorWarningBgHover": "#fff1b8",
      "colorWarningText": "#faad14",
      "colorErrorText": "#ff4d4f",
      "activeBg": "#ffffff",
      "hoverBg": "#ffffff",
      "inputFontSize": 14,
      "inputFontSizeLG": 16,
      "inputFontSizeSM": 12,
      "fontFamily": "Inter",
      "labelFontSize": "14",
      "labelColor": "#a6a6a6",
      "labelLineHeight": 1.2,
      "labelHeight": 10
    },
    "Transfer": {
      "headerHeight": 48,
      "headerPaddingVertical": 16,
      "headerPaddingHorizontal": 16,
      "headerFontSize": 16,
      "headerBg": "#fafafa",
      "headerBorderColor": "#d9d9d9",
      "panelBorderRadius": 6,
      "panelBorderColor": "#d9d9d9",
      "panelLeftMaxWidth": "550px",
      "panelRightMaxWidth": "800px",
      "maxHeight": 800
    },
    "Segmented": {
      "segmentedBgColorSelected": "#ffffff",
      "paddingXXS": 4,
      "marginSM": 12,
      "lineWidthBold": 2,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSizeLG": 16,
      "fontSize": 14,
      "controlPaddingHorizontalSM": 8,
      "controlPaddingHorizontal": 12,
      "controlHeightSM": 24,
      "controlHeightLG": 40,
      "controlHeight": 32,
      "borderRadiusXS": 2,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "borderRadius": 6,
      "colorTextLabel": "rgba(0, 0, 0, 0.65)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
      "colorFill": "rgba(0, 0, 0, 0.15)",
      "colorBgLayout": "#f5f5f5",
      "colorBgElevated": "#ffffff",
      "segmentedGroupBg": "rgba(0, 0, 0, 0.04)",
      "itemSelectedColor": "rgba(0, 0, 0, 0.88)",
      "itemSelectedBg": "#ffffff",
      "itemHoverColor": "rgba(0, 0, 0, 0.88)",
      "itemHoverBg": "rgba(0, 0, 0, 0.06)",
      "itemColor": "rgba(0, 0, 0, 0.65)",
      "itemActiveBg": "rgba(0, 0, 0, 0.15)",
      "trackPadding": 2,
      "trackBg": "#f5f5f5",
      "fontFamily": "Inter"
    },
    "Switch": {
      "trackPadding": 2,
      "trackMinWidthSM": 28,
      "trackMinWidth": 44,
      "trackHeightSM": 16,
      "trackHeight": 22,
      "handleSizeSM": 12,
      "handleSize": 18,
      "marginXXS": 4,
      "lineWidthFocus": 4,
      "lineHeight": 1.2,
      "fontSizeSM": 12,
      "fontSizeIcon": 12,
      "fontSize": 14,
      "controlHeight": 32,
      "colorWhite": "#ffffff",
      "colorTextTertiary": "rgba(0, 0, 0, 0.45)",
      "colorTextQuaternary": "rgba(0, 0, 0, 0.25)",
      "colorTextLightSolid": "#ffffff",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimaryBorder": "#ffcb9e",
      "colorPrimary": "#f37022",
      "handleBg": "#ffffff",
      "fontFamily": "Inter"
    },
    "TimePicker": {
      "timeColumnWidth": 56,
      "timeColumnHeight": 224,
      "timeCellHeight": 28,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "sizePopupArrow": 16,
      "paddingXXS": 4,
      "paddingXS": 8,
      "paddingSM": 12,
      "padding": 16,
      "marginXXS": 4,
      "marginXS": 8,
      "lineWidthBold": 2,
      "lineWidth": 1,
      "lineHeightLG": 1.4,
      "lineHeight": 1.5714285714285714,
      "fontWeightStrong": 600,
      "fontSizeLG": 16,
      "fontSize": 14,
      "controlPaddingHorizontalSM": 8,
      "controlPaddingHorizontal": 12,
      "controlOutlineWidth": 2,
      "controlOutline": "rgba(243, 112, 34, 0.1)",
      "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
      "controlItemBgActive": "#fff8f0",
      "controlHeightSM": 24,
      "controlHeightLG": 40,
      "controlHeight": 32,
      "borderRadiusXS": 2,
      "borderRadius": 6,
      "colorWarningOutline": "rgba(255, 215, 5, 0.1)",
      "colorWarning": "#faad14",
      "colorTextQuaternary": "rgba(0, 0, 0, 0.25)",
      "colorTextPlaceholder": "rgba(0, 0, 0, 0.25)",
      "colorTextLightSolid": "#ffffff",
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimaryBorder": "#ffcb9e",
      "colorPrimary": "#f37022",
      "colorLinkHover": "#ff944d",
      "colorLinkActive": "#cc5012",
      "colorLink": "#f37022",
      "colorIconHover": "rgba(0, 0, 0, 0.88)",
      "colorIcon": "rgba(0, 0, 0, 0.45)",
      "colorFillAlter": "rgba(0, 0, 0, 0.02)",
      "colorErrorOutline": "rgba(255, 38, 6, 0.06)",
      "colorError": "#ff4d4f",
      "colorBorder": "#d9d9d9",
      "colorBgElevated": "#ffffff",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "colorBgContainer": "#ffffff",
      "hoverBorderColor": "#ff944d",
      "cellHoverBg": "rgba(0, 0, 0, 0.04)",
      "cellHeight": 24,
      "activeBorderColor": "#f37022",
      "paddingInline": 11,
      "paddingInlineLG": 11,
      "paddingInlineSM": 7,
      "activeBg": "#ffffff",
      "hoverBg": "#ffffff",
      "cellBgDisabled": "rgba(0, 0, 0, 0.04)",
      "cellActiveWithRangeBg": "#fff8f0",
      "cellHoverWithRangeBg": "#c8dfff",
      "cellRangeBorderColor": "#7cb3ff",
      "multipleItemBg": "rgba(0, 0, 0, 0.06)",
      "multipleItemBorderColor": "rgba(0, 0, 0, 0)",
      "multipleItemBorderColorDisabled": "rgba(0, 0, 0, 0)",
      "multipleItemColorDisabled": "rgba(0, 0, 0, 0.25)",
      "multipleSelectorBgDisabled": "rgba(0, 0, 0, 0.04)",
      "cellWidth": 36,
      "multipleItemHeight": 24,
      "multipleItemHeightLG": 32,
      "multipleItemHeightSM": 16,
      "paddingBlock": 4,
      "paddingBlockLG": 7,
      "paddingBlockSM": 0,
      "presetsMaxWidth": 200,
      "presetsWidth": 120,
      "textHeight": 40,
      "withoutTimeCellHeight": 66,
      "inputFontSize": 14,
      "inputFontSizeLG": 16,
      "inputFontSizeSM": 12,
      "fontFamily": "Inter"
    },
    "Timeline": {
      "itemPaddingBottom": 20,
      "paddingXXS": 4,
      "padding": 16,
      "marginXXS": 4,
      "marginXS": 8,
      "marginSM": 12,
      "margin": 16,
      "lineWidthBold": 2,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSizeSM": 12,
      "fontSize": 14,
      "controlHeightLG": 40,
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSuccess": "#52c41a",
      "colorPrimary": "#f37022",
      "colorError": "#ff4d4f",
      "colorBgContainer": "#ffffff",
      "tailColor": "rgba(0, 0, 0, 0.06)",
      "dotBg": "#ffffff",
      "fontFamily": "Inter"
    },
    "Tabs": {
      "horizontalItemGutter": 32,
      "cardGutter": 2,
      "paddingXXS": 4,
      "paddingXS": 8,
      "paddingSM": 12,
      "paddingLG": 24,
      "padding": 16,
      "marginXXS": 4,
      "marginXS": 8,
      "marginSM": 12,
      "margin": 16,
      "lineWidthFocus": 4,
      "lineWidthBold": 2,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSizeSM": 12,
      "fontSizeLG": 16,
      "fontSize": 14,
      "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
      "controlHeightLG": 40,
      "controlHeight": 32,
      "borderRadiusLG": 8,
      "borderRadius": 6,
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimaryBorder": "#ffcb9e",
      "colorPrimaryActive": "#cc5012",
      "colorPrimary": "#f37022",
      "colorFillAlter": "rgba(0, 0, 0, 0.02)",
      "colorBorderSecondary": "#f0f0f0",
      "colorBorder": "#d9d9d9",
      "colorBgContainer": "#ffffff",
      "itemSelectedColor": "#f37022",
      "itemHoverColor": "#ff944d",
      "itemColor": "rgba(0, 0, 0, 0.88)",
      "itemActiveColor": "#cc5012",
      "inkBarColor": "#f37022",
      "cardHeight": 40,
      "cardBg": "rgba(0, 0, 0, 0.02)",
      "titleFontSize": 14,
      "titleFontSizeLG": 16,
      "titleFontSizeSM": 14,
      "fontFamily": "Inter",
      "iconSize": 14,
      "iconSizeSM": 14,
      "iconSizeLG": 16
    },
    "Table": {
      "stickyScrollBarBorderRadius": 100,
      "headerSplitColor": "#f0f0f0",
      "headerBg": "#fafafa",
      "footerBg": "#fafafa",
      "paddingXXS": 4,
      "paddingXS": 8,
      "paddingSM": 12,
      "padding": 16,
      "marginXXS": 4,
      "margin": 16,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontWeightStrong": 600,
      "fontSizeSM": 12,
      "fontSizeIcon": 12,
      "fontSize": 14,
      "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
      "controlItemBgActiveHover": "#ffe3c7",
      "controlItemBgActive": "#fff8f0",
      "controlInteractiveSize": 16,
      "controlHeight": 32,
      "borderRadiusLG": 8,
      "borderRadius": 6,
      "colorTextPlaceholder": "rgba(0, 0, 0, 0.25)",
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "colorPrimary": "#f37022",
      "colorLinkHover": "#ff944d",
      "colorLinkActive": "#cc5012",
      "colorLink": "#f37022",
      "colorIconHover": "rgba(0, 0, 0, 0.88)",
      "colorIcon": "rgba(0, 0, 0, 0.45)",
      "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
      "colorFillContent": "rgba(0, 0, 0, 0.06)",
      "colorFillAlter": "rgba(0, 0, 0, 0.02)",
      "colorBorderSecondary": "#f0f0f0",
      "colorBgContainer": "#ffffff",
      "rowSelectedHoverBg": "#ffe3c7",
      "headerFilterHoverBg": "rgba(0, 0, 0, 0.06)",
      "headerColor": "rgba(0, 0, 0, 0.88)",
      "headerBorderRadius": 8,
      "footerColor": "rgba(0, 0, 0, 0.88)",
      "filterDropdownMenuBg": "#ffffff",
      "filterDropdownBg": "#ffffff",
      "cellPaddingInlineSM": 8,
      "cellPaddingInlineMD": 8,
      "cellPaddingInline": 16,
      "cellPaddingBlockSM": 8,
      "cellPaddingBlockMD": 12,
      "cellPaddingBlock": 16,
      "borderColor": "#f0f0f0",
      "rowHoverBg": "#fafafa",
      "headerSortActiveBg": "rgba(0, 0, 0, 0.06)",
      "bodySortBg": "#fafafa",
      "headerSortHoverBg": "rgba(0, 0, 0, 0.06)",
      "cellFontSize": 14,
      "cellFontSizeMD": 14,
      "cellFontSizeSM": 14,
      "fontFamily": "Inter",
      "rowSelectedBg": "#fff8f0",
      "subtextFontSize": 12,
      "subtextFontWeight": 400,
      "subtextColor": "rgba(0, 0, 0, 0.45)",
      "columnChooserOptionColor": "rgba(0, 0, 0, 0.88)",
      "columnChooserOptionFontSize": 14,
      "columnChooserOptionHoverBg": "rgba(0, 0, 0, 0.04)",
      "columnChooserOptionSelectedFontWeight": 600,
      "columnChooserOptionFontWeight": 400,
      "columnChooserOptionPaddingHorizontal": 12,
      "columnChooserOptionPaddingVertical": 5,
      "columnChooserOptionIconColor": "#f37022",
      "columnChooserOptionDisabledColor": "rgba(0, 0, 0, 0.35)",
      "columnChooserOptionIconWidth": 16,
      "columnChooserOptionIconHeight": 16,
      "columnChooserPaddingVertical": 4,
      "columnChooserPaddingHorizontal": 4,
      "columnChooserMaxHeight": 294
    },
    "Steps": {
      "dotSize": 8,
      "dotCurrentSize": 10,
      "descriptionMaxWidth": 140,
      "paddingXXS": 4,
      "paddingXS": 8,
      "paddingSM": 12,
      "paddingLG": 24,
      "padding": 16,
      "marginXXS": 4,
      "marginXS": 8,
      "marginSM": 12,
      "marginLG": 24,
      "margin": 16,
      "lineWidthFocus": 4,
      "lineWidthBold": 2,
      "lineWidth": 1,
      "lineHeightSM": 20,
      "lineHeight": 1.2,
      "fontWeightStrong": 600,
      "fontSizeSM": 12,
      "fontSizeLG": 16,
      "fontSizeIcon": 12,
      "fontSizeHeading3": 24,
      "fontSize": 14,
      "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
      "controlItemBgActive": "#fff8f0",
      "controlHeightLG": 40,
      "borderRadiusSM": 4,
      "colorTextQuaternary": "rgba(0, 0, 0, 0.25)",
      "colorTextLightSolid": "#ffffff",
      "colorTextLabel": "rgba(0, 0, 0, 0.65)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "colorPrimaryBorder": "#ffcb9e",
      "colorPrimary": "#f37022",
      "colorFillContent": "rgba(0, 0, 0, 0.06)",
      "colorError": "#ff4d4f",
      "colorBorderSecondary": "#f0f0f0",
      "colorBorderBg": "#ffffff",
      "colorBgContainer": "#ffffff",
      "titleLineHeight": 32,
      "iconSizeSM": 24,
      "iconSize": 32,
      "finishIconBorderColor": "#1677ff",
      "customIconFontSize": 24,
      "iconFontSize": 14,
      "fontFamily": "Inter"
    },
    "Spin": {
      "dotSizeSM": 14,
      "dotSize": 20,
      "contentHeight": 400,
      "marginXXS": 4,
      "lineHeight": 1.2,
      "fontSize": 14,
      "controlHeightLG": 40,
      "controlHeight": 32,
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimary": "#f37022",
      "colorBgContainer": "#ffffff",
      "dotSizeLG": 32,
      "fontFamily": "Inter"
    },
    "Slider": {
      "railSize": 4,
      "handleSizeHover": 12,
      "dotSize": 8,
      "controlSize": 10,
      "handleSize": 10,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSize": 14,
      "controlHeightSM": 24,
      "controlHeightLG": 40,
      "controlHeight": 32,
      "borderRadiusXS": 2,
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimaryBorderHover": "#ffb175",
      "colorPrimaryBorder": "#ffcb9e",
      "colorPrimary": "#f37022",
      "colorFillTertiary": "rgba(0, 0, 0, 0.04)",
      "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
      "colorFillContentHover": "rgba(0, 0, 0, 0.15)",
      "colorBorderSecondary": "#f0f0f0",
      "colorBgElevated": "#ffffff",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "colorBgContainer": "#ffffff",
      "trackHoverBg": "#ffb175",
      "trackBgDisabled": "rgba(0, 0, 0, 0.04)",
      "trackBg": "#ffcb9e",
      "railHoverBg": "rgba(0, 0, 0, 0.06)",
      "railBg": "rgba(0, 0, 0, 0.04)",
      "handleColor": "#ffcb9e",
      "handleActiveColor": "#f37022",
      "dotBorderColor": "#f0f0f0",
      "dotActiveBorderColor": "#ffcb9e",
      "handleColorDisabled": "#bfbfbf",
      "fontFamily": "Inter"
    },
    "Rate": {
      "rateStarSize": 20,
      "marginXS": 8,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSize": 14,
      "controlHeightLG": 40,
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorFillContent": "rgba(0, 0, 0, 0.06)",
      "fontFamily": "Inter"
    },
    "Radio": {
      "radioSize": 16,
      "dotSize": 8,
      "buttonPaddingInline": 15,
      "paddingXS": 8,
      "padding": 16,
      "marginXS": 8,
      "lineWidthFocus": 4,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSizeLG": 16,
      "fontSize": 14,
      "controlOutlineWidth": 2,
      "controlOutline": "rgba(243, 112, 34, 0.1)",
      "controlItemBgActiveDisabled": "rgba(0, 0, 0, 0.15)",
      "controlHeightSM": 24,
      "controlHeightLG": 40,
      "controlHeight": 32,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "borderRadius": 6,
      "colorWhite": "#ffffff",
      "colorTextLightSolid": "#ffffff",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimaryBorder": "#ffcb9e",
      "colorPrimaryActive": "#cc5012",
      "colorPrimary": "#f37022",
      "colorBorder": "#d9d9d9",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "colorBgContainer": "#ffffff",
      "wrapperMarginInlineEnd": 8,
      "dotColorDisabled": "rgba(0, 0, 0, 0.25)",
      "buttonSolidCheckedHoverBg": "#ff944d",
      "buttonSolidCheckedColor": "#ffffff",
      "buttonSolidCheckedBg": "#f37022",
      "buttonSolidCheckedActiveBg": "#cc5012",
      "buttonColor": "rgba(0, 0, 0, 0.88)",
      "buttonCheckedColorDisabled": "rgba(0, 0, 0, 0.25)",
      "buttonCheckedBgDisabled": "rgba(0, 0, 0, 0.15)",
      "buttonCheckedBg": "#ffffff",
      "buttonBg": "#ffffff",
      "fontFamily": "Inter"
    },
    "Popover": {
      "titleMinWidth": 265,
      "sizePopupArrow": 16,
      "paddingSM": 12,
      "padding": 16,
      "marginXS": 8,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontWeightStrong": 600,
      "fontSize": 14,
      "controlHeight": 32,
      "borderRadiusXS": 2,
      "borderRadiusLG": 8,
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "colorBgElevated": "#ffffff",
      "fontFamily": "Inter",
      "maxWidth": 600,
      "maxHeight": 450
    },
    "Notification": {
      "width": 384,
      "paddingMD": 20,
      "paddingLG": 24,
      "paddingContentHorizontalLG": 24,
      "marginXS": 8,
      "marginSM": 12,
      "marginLG": 24,
      "margin": 16,
      "lineHeight": 1.2,
      "fontSizeLG": 16,
      "fontSize": 14,
      "controlHeightLG": 40,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "colorWarning": "#faad14",
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSuccess": "#52c41a",
      "colorInfo": "rgba(0, 0, 0, 0.3)",
      "colorIconHover": "rgba(0, 0, 0, 0.88)",
      "colorIcon": "rgba(0, 0, 0, 0.45)",
      "colorError": "#ff4d4f",
      "colorBgElevated": "#ffffff",
      "lineHeightLG": 1.4,
      "lineWidthFocus": 4,
      "fontFamily": "Inter"
    },
    "Tooltip": {
      "paddingSM": 12,
      "sizePopupArrow": 16,
      "paddingXS": 8,
      "fontSize": 14,
      "fontWeight": 400,
      "controlHeight": 32,
      "borderRadiusXS": 2,
      "borderRadius": 6,
      "colorTextLightSolid": "#ffffff",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorBgSpotlight": "rgba(0, 0, 0, 0.85)",
      "fontFamily": "Inter"
    },
    "Menu": {
      "subMenuItemBg": "rgba(0, 0, 0, 0.02)",
      "darkSubMenuItemBg": "#212121",
      "darkItemDisabledColor": "rgba(255, 255, 255, 0.25)",
      "darkItemColor": "rgba(255, 255, 255, 0.65)",
      "darkGroupTitleColor": "rgba(255, 255, 255, 0.65)",
      "darkItemBg": "#212121",
      "paddingXS": 8,
      "paddingXL": 32,
      "padding": 16,
      "marginXXS": 4,
      "marginXS": 8,
      "margin": 16,
      "lineWidthFocus": 4,
      "lineWidthBold": 2,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSizeLG": 16,
      "fontSize": 14,
      "controlItemBgActive": "#fff8f0",
      "controlHeightSM": 24,
      "controlHeightLG": 40,
      "borderRadius": 6,
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "colorPrimaryBorder": "#ffcb9e",
      "colorPrimary": "#f37022",
      "colorFillContent": "rgba(0, 0, 0, 0.06)",
      "colorErrorHover": "#ff7875",
      "colorErrorBg": "#fff2f0",
      "colorError": "#ff4d4f",
      "colorBgElevated": "#ffffff",
      "colorBgContainer": "#ffffff",
      "subMenuItemBorderRadius": 4,
      "popupBg": "#ffffff",
      "itemSelectedColor": "#f37022",
      "itemSelectedBg": "#fff8f0",
      "itemHoverColor": "rgba(0, 0, 0, 0.88)",
      "itemHoverBg": "rgba(0, 0, 0, 0.06)",
      "itemHeight": 40,
      "itemDisabledColor": "rgba(0, 0, 0, 0.25)",
      "itemColor": "rgba(0, 0, 0, 0.88)",
      "itemBorderRadius": 3,
      "itemBg": "#ffffff",
      "iconSize": 16,
      "horizontalItemSelectedColor": "#f37022",
      "horizontalItemSelectedBg": "rgba(0, 0, 0, 0)",
      "horizontalItemHoverColor": "#f37022",
      "horizontalItemHoverBg": "rgba(0, 0, 0, 0)",
      "groupTitleColor": "rgba(0, 0, 0, 0.45)",
      "darkItemSelectedColor": "#ffffff",
      "darkItemSelectedBg": "#f37022",
      "darkItemHoverColor": "#ffffff",
      "darkItemHoverBg": "rgba(0, 0, 0, 0)",
      "collapsedIconSize": 16,
      "darkPopupBg": "#212121",
      "activeBarBorderWidth": 1,
      "collapsedWidth": 80,
      "dropdownWidth": 160,
      "itemMarginBlock": 4,
      "itemMarginInline": 4,
      "iconMarginInlineEnd": 10,
      "groupTitleFontSize": 14,
      "groupTitleLineHeight": 1.2,
      "fontFamily": "Inter"
    },
    "InputNumber": {
      "paddingInlineSM": 7,
      "paddingInlineLG": 11,
      "paddingInline": 11,
      "paddingBlockSM": 0,
      "paddingBlockLG": 7,
      "paddingBlock": 4,
      "handleWidth": 22,
      "controlWidth": 90,
      "paddingXXS": 4,
      "paddingXS": 8,
      "paddingSM": 12,
      "lineWidth": 1,
      "lineHeightLG": 1.4,
      "lineHeight": 1.2,
      "fontSizeLG": 16,
      "fontSize": 14,
      "controlPaddingHorizontalSM": 8,
      "controlPaddingHorizontal": 12,
      "controlHeightSM": 24,
      "controlHeightLG": 40,
      "controlHeight": 32,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "borderRadius": 6,
      "colorWarningBorderHover": "#ffd666",
      "colorWarning": "#faad14",
      "colorTextPlaceholder": "rgba(0, 0, 0, 0.25)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimary": "#f37022",
      "colorFillAlter": "rgba(0, 0, 0, 0.02)",
      "colorErrorBorderHover": "#ffa39e",
      "colorError": "#ff4d4f",
      "colorBorder": "#d9d9d9",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "colorBgContainer": "#ffffff",
      "hoverBorderColor": "#ff944d",
      "handleHoverColor": "#f37022",
      "handleBorderColor": "#d9d9d9",
      "handleBg": "#ffffff",
      "handleActiveBg": "rgba(0, 0, 0, 0.02)",
      "addonBg": "rgba(0, 0, 0, 0.02)",
      "activeBorderColor": "#f37022",
      "activeBg": "#ffffff",
      "hoverBg": "#ffffff",
      "inputFontSize": 14,
      "inputFontSizeLG": 16,
      "inputFontSizeSM": 12,
      "fontFamily": "Inter"
    },
    "Image": {
      "previewOperationSize": 18,
      "previewOperationHoverColor": "rgba(255, 255, 255, 0.85)",
      "previewOperationColorDisabled": "rgba(255, 255, 255, 0.25)",
      "previewOperationColor": "rgba(255, 255, 255, 0.65)",
      "paddingXXS": 4,
      "paddingSM": 12,
      "paddingLG": 24,
      "marginXXS": 4,
      "marginXL": 32,
      "marginSM": 12,
      "margin": 16,
      "fontSizeIcon": 12,
      "controlHeightLG": 40,
      "colorTextLightSolid": "#ffffff",
      "colorBgMask": "rgba(0, 0, 0, 0.45)",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)"
    },
    "Card": {
      "headerHeightSM": 38,
      "headerHeight": 56,
      "paddingXS": 8,
      "paddingSM": 12,
      "paddingLG": 24,
      "padding": 16,
      "marginXXS": 4,
      "marginXS": 8,
      "lineWidth": 1,
      "lineHeightLG": 1.4,
      "lineHeight": 1.2,
      "fontWeightStrong": 600,
      "fontSize": 14,
      "borderRadiusLG": 8,
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimary": "#f37022",
      "colorFillAlter": "rgba(0, 0, 0, 0.02)",
      "colorBorderSecondary": "#d9d9d9",
      "colorBgContainer": "#ffffff",
      "headerBg": "rgba(0, 0, 0, 0)",
      "headerFontSize": 16,
      "headerFontSizeSM": 14,
      "fontHeight": 22,
      "fontSizeLG": 16,
      "fontFamily": "Inter",
      "innerHeaderFontSize": 16,
      "innerHeaderHeight": 48,
      "innerHeaderBg": "rgba(0, 0, 0, 0.02)",
      "innerHeaderLineHeight": "1.5",
      "innerHeaderPaddingHorizontal": 16,
      "innerContentPaddingVertical": 16,
      "innerContentPaddingHorizontal": 16
    },
    "Carousel": {
      "dotWidth": 16,
      "dotHeight": 3,
      "dotActiveWidth": 24,
      "marginXXS": 4,
      "lineHeight": 1.2,
      "fontSize": 14,
      "controlHeightSM": 24,
      "controlHeightLG": 40,
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorBgContainer": "#ffffff",
      "fontFamily": "Inter"
    },
    "Cascader": {
      "dropdownHeight": 180,
      "controlWidth": 184,
      "controlItemWidth": 111,
      "paddingXXS": 4,
      "paddingXS": 8,
      "paddingSM": 12,
      "marginXS": 8,
      "lineWidthFocus": 4,
      "lineWidthBold": 2,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontWeightStrong": 600,
      "fontSizeLG": 16,
      "fontSizeIcon": 12,
      "fontSize": 14,
      "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
      "controlItemBgActive": "#fff8f0",
      "controlInteractiveSize": 16,
      "controlHeight": 32,
      "borderRadiusSM": 4,
      "colorWhite": "#ffffff",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimaryBorder": "#ffcb9e",
      "colorPrimary": "#f37022",
      "colorBorder": "#d9d9d9",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "colorBgContainer": "#ffffff",
      "optionSelectedBg": "#fff8f0",
      "menuPadding": 4,
      "optionSelectedFontWeight": 600,
      "fontFamily": "Inter"
    },
    "Calendar": {
      "yearControlWidth": 80,
      "monthControlWidth": 70,
      "controlHeight": 32,
      "screenXS": 480,
      "paddingXXS": 4,
      "paddingXS": 8,
      "paddingSM": 12,
      "padding": 16,
      "marginXXS": 4,
      "marginXS": 8,
      "lineWidthBold": 2,
      "lineWidth": 1,
      "lineHeightSM": 20,
      "lineHeight": 1.2,
      "fontWeightStrong": 600,
      "fontSizeSM": 12,
      "fontSize": 14,
      "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
      "controlItemBgActive": "#fff8f0",
      "controlHeightSM": 24,
      "controlHeightLG": 40,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "colorTextLightSolid": "#ffffff",
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "colorPrimary": "#f37022",
      "colorLinkHover": "#ff944d",
      "colorLinkActive": "#cc5012",
      "colorLink": "#f37022",
      "colorIconHover": "rgba(0, 0, 0, 0.88)",
      "colorIcon": "rgba(0, 0, 0, 0.45)",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "colorBgContainer": "#ffffff",
      "itemActiveBg": "#fff8f0",
      "fullPanelBg": "#ffffff",
      "fullBg": "#ffffff",
      "fontHeightSM": 20,
      "fontFamily": "Inter"
    },
    "Button": {
      "borderRadius": 3,
      "borderRadiusLG": 3,
      "borderRadiusSM": 3,
      "colorBgContainer": "#ffffff",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "contentFontSize": 14,
      "contentFontSizeLG": 16,
      "contentFontSizeSM": 14,
      "contentLineHeight": 1.2,
      "contentLineHeightLG": 1.4,
      "contentLineHeightSM": 1.2,
      "controlHeight": 32,
      "controlHeightLG": 40,
      "controlHeightSM": 24,
      "controlOutline": "rgba(243, 112, 34, 0.1)",
      "controlOutlineWidth": 2,
      "dashedBg": "#ffffff",
      "dashedBorderColor": "#d9d9d9",
      "dashedColor": "rgba(0, 0, 0, 0.88)",
      "dashedDangerBg": "#ffffff",
      "dashedDangerBorderColor": "#ff4d4f",
      "dashedDangerColor": "#ff4d4f",
      "dashedDangerDisabledBg": "rgba(0, 0, 0, 0)",
      "dashedDangerDisabledBorderColor": "#d9d9d9",
      "dashedDangerDisabledColor": "rgba(0, 0, 0, 0.25)",
      "dashedDangerFocusedBg": "#ffffff",
      "dashedDangerFocusedBorderColor": "#ff7875",
      "dashedDangerFocusedColor": "#ff7875",
      "dashedDangerHoverBg": "#ffffff",
      "dashedDangerHoverBorderColor": "#ff7875",
      "dashedDangerHoverColor": "#ff7875",
      "dashedDangerPressedBg": "#ffffff",
      "dashedDangerPressedBorderColor": "#f5222d",
      "dashedDangerPressedColor": "#f5222d",
      "dashedDisabledBg": "rgba(0, 0, 0, 0)",
      "dashedDisabledBorderColor": "#d9d9d9",
      "dashedDisabledColor": "rgba(0, 0, 0, 0.25)",
      "dashedFocusedBg": "#ffffff",
      "dashedFocusedBorderColor": "#ff944d",
      "dashedFocusedColor": "#ff944d",
      "dashedGhostBg": "rgba(0, 0, 0, 0)",
      "dashedGhostBorderColor": "#f37022",
      "dashedGhostColor": "#f37022",
      "dashedGhostDangerBg": "rgba(0, 0, 0, 0)",
      "dashedGhostDangerBorderColor": "#ff4d4f",
      "dashedGhostDangerColor": "#ff4d4f",
      "dashedGhostDangerDisabledBg": "rgba(0, 0, 0, 0)",
      "dashedGhostDangerDisabledBorderColor": "rgba(0, 0, 0, 0.25)",
      "dashedGhostDangerDisabledColor": "rgba(0, 0, 0, 0.25)",
      "dashedGhostDangerFocusedBg": "rgba(0, 0, 0, 0)",
      "dashedGhostDangerFocusedBorderColor": "#FF7875",
      "dashedGhostDangerFocusedColor": "#FF7875",
      "dashedGhostDangerHoverBg": "rgba(0, 0, 0, 0)",
      "dashedGhostDangerHoverBorderColor": "#FF7875",
      "dashedGhostDangerHoverColor": "#FF7875",
      "dashedGhostDangerPressedBg": "rgba(0, 0, 0, 0)",
      "dashedGhostDangerPressedBorderColor": "#D9363E",
      "dashedGhostDangerPressedColor": "#D9363E",
      "dashedGhostDisabledBg": "rgba(0, 0, 0, 0)",
      "dashedGhostDisabledBorderColor": "rgba(0, 0, 0, 0.25)",
      "dashedGhostDisabledColor": "rgba(0, 0, 0, 0.25)",
      "dashedGhostFocusedBg": "rgba(0, 0, 0, 0)",
      "dashedGhostFocusedBorderColor": "#FF944D",
      "dashedGhostFocusedColor": "#FF944D",
      "dashedGhostHoverBg": "rgba(0, 0, 0, 0)",
      "dashedGhostHoverBorderColor": "#FF944D",
      "dashedGhostHoverColor": "#FF944D",
      "dashedGhostPressedBg": "rgba(0, 0, 0, 0)",
      "dashedGhostPressedBorderColor": "#cc5012",
      "dashedGhostPressedColor": "#cc5012",
      "dashedHoverBg": "#ffffff",
      "dashedHoverBorderColor": "#ff944d",
      "dashedHoverColor": "#ff944d",
      "dashedPressedBg": "#ffffff",
      "dashedPressedBorderColor": "#cc5012",
      "dashedPressedColor": "#cc5012",
      "defaultBg": "#ffffff",
      "defaultBorderColor": "#d9d9d9",
      "defaultColor": "#000000",
      "defaultDangerBg": "#ffffff",
      "defaultDangerBorderColor": "#ff4d4f",
      "defaultDangerColor": "#ff4d4f",
      "defaultDangerDisabledBg": "rgba(0, 0, 0, 0)",
      "defaultDangerDisabledBorderColor": "#d9d9d9",
      "defaultDangerDisabledColor": "rgba(0, 0, 0, 0.25)",
      "defaultDangerFocusedBg": "#ffffff",
      "defaultDangerFocusedBorderColor": "#ff7875",
      "defaultDangerFocusedColor": "#ff7875",
      "defaultDangerHoverBg": "#ffffff",
      "defaultDangerHoverBorderColor": "#ff4d4f",
      "defaultDangerHoverColor": "#ff7875",
      "defaultDangerPressedBg": "#ffffff",
      "defaultDangerPressedBorderColor": "#f5222d",
      "defaultDangerPressedColor": "#f5222d",
      "defaultDisabledBg": "rgba(0, 0, 0, 0)",
      "defaultDisabledBorderColor": "#d9d9d9",
      "defaultDisabledColor": "rgba(0, 0, 0, 0.25)",
      "defaultFocusedBg": "#ffffff",
      "defaultFocusedBorderColor": "#ff944d",
      "defaultFocusedColor": "#ff944d",
      "defaultHoverBg": "#ffffff",
      "defaultGhostBg": "rgba(0, 0, 0, 0)",
      "defaultGhostBorderColor": "#f37022",
      "defaultGhostColor": "#f37022",
      "defaultGhostDangerBg": "rgba(0, 0, 0, 0)",
      "defaultGhostDangerBorderColor": "#ff4d4f",
      "defaultGhostDangerColor": "#ff4d4f",
      "defaultGhostDangerDisabledBg": "rgba(0, 0, 0, 0)",
      "defaultGhostDangerDisabledBorderColor": "rgba(0, 0, 0, 0.25)",
      "defaultGhostDangerDisabledColor": "rgba(0, 0, 0, 0.25)",
      "defaultGhostDangerFocusedBg": "rgba(0, 0, 0, 0)",
      "defaultGhostDangerFocusedBorderColor": "#FF7875",
      "defaultGhostDangerFocusedColor": "#FF7875",
      "defaultGhostDangerHoverBg": "rgba(0, 0, 0, 0)",
      "defaultGhostDangerHoverBorderColor": "#FF7875",
      "defaultGhostDangerHoverColor": "#FF7875",
      "defaultGhostDangerPressedBg": "rgba(0, 0, 0, 0)",
      "defaultGhostDangerPressedBorderColor": "#D9363E",
      "defaultGhostDangerPressedColor": "#D9363E",
      "defaultGhostDisabledBg": "rgba(0, 0, 0, 0)",
      "defaultGhostDisabledBorderColor": "#d9d9d9",
      "defaultGhostDisabledColor": "rgba(0, 0, 0, 0.25)",
      "defaultGhostFocusedBg": "rgba(0, 0, 0, 0)",
      "defaultGhostFocusedBorderColor": "#FF944D",
      "defaultGhostFocusedColor": "#FF944D",
      "defaultGhostHoverBg": "rgba(0, 0, 0, 0)",
      "defaultGhostHoverBorderColor": "#FF944D",
      "defaultGhostHoverColor": "#FF944D",
      "defaultGhostPressedBg": "rgba(0, 0, 0, 0)",
      "defaultGhostPressedBorderColor": "#cc5012",
      "defaultGhostPressedColor": "#cc5012",
      "defaultHoverBorderColor": "#ff944d",
      "defaultHoverColor": "#ff944d",
      "defaultPressedBg": "#ffffff",
      "defaultPressedBorderColor": "#cc5012",
      "defaultPressedColor": "#cc5012",
      "fontWeight": 400,
      "groupBorderColor": "#ff944d",
      "iconDashedColor": "rgba(0, 0, 0, 0.65)",
      "iconDashedDangerColor": "#ff4d4f",
      "iconDashedDangerDisabledColor": "rgba(0, 0, 0, 0.25)",
      "iconDashedDangerFocusedColor": "#ff7875",
      "iconDashedDangerHoverColor": "#ff7875",
      "iconDashedDangerPressedColor": "#f5222d",
      "iconDashedDisabledColor": "rgba(0, 0, 0, 0.25)",
      "iconDashedFocusedColor": "#ff944d",
      "iconDashedGhostColor": "#f37022",
      "iconDashedGhostDangerColor": "#ff4d4f",
      "iconDashedGhostDangerDisabledColor": "rgba(0, 0, 0, 0.25)",
      "iconDashedGhostDangerFocusedColor": "#FF7875",
      "iconDashedGhostDangerHoverColor": "#FF7875",
      "iconDashedGhostDangerPressedColor": "#D9363E",
      "iconDashedGhostDisabledColor": "rgba(0, 0, 0, 0.25)",
      "iconDashedGhostFocusedColor": "#FF944D",
      "iconDashedGhostHoverColor": "#FF944D",
      "iconDashedGhostPressedColor": "#cc5012",
      "iconDashedHoverColor": "#ff944d",
      "iconDashedPressedColor": "#cc5012",
      "iconDefaultColor": "rgba(0, 0, 0, 0.65)",
      "iconDefaultDangerColor": "#f5222d",
      "iconDefaultDangerDisabledColor": "rgba(0, 0, 0, 0.25)",
      "iconDefaultDangerFocusedColor": "#ff7875",
      "iconDefaultDangerHoverColor": "#ff7875",
      "iconDefaultDangerPressedColor": "#f5222d",
      "iconDefaultDisabledColor": "rgba(0, 0, 0, 0.25)",
      "iconDefaultFocusedColor": "#ff944d",
      "iconDefaultGhostColor": "#f37022",
      "iconDefaultGhostDangerColor": "#f5222d",
      "iconDefaultGhostDangerDisabledColor": "rgba(0, 0, 0, 0.25)",
      "iconDefaultGhostDangerFocusedColor": "#FF7875",
      "iconDefaultGhostDangerHoverColor": "#FF7875",
      "iconDefaultGhostDangerPressedColor": "#D9363E",
      "iconDefaultGhostDisabledColor": "rgba(0, 0, 0, 0.25)",
      "iconDefaultGhostFocusedColor": "#FF944D",
      "iconDefaultGhostHoverColor": "#FF944D",
      "iconDefaultGhostPressedColor": "#cc5012",
      "iconDefaultHoverColor": "#ff944d",
      "iconDefaultPressedColor": "#cc5012",
      "iconLinkColor": "#f37022",
      "iconLinkDangerColor": "#ff4d4f",
      "iconLinkDangerDisabledColor": "#ffa39e",
      "iconLinkDangerFocusedColor": "#ff7875",
      "iconLinkDangerHoverColor": "#ff7875",
      "iconLinkDangerPressedColor": "#f5222d",
      "iconLinkDisabledColor": "#ffb175",
      "iconLinkFocusedColor": "#ff944d",
      "iconLinkHoverColor": "#ff944d",
      "iconLinkPressedColor": "#f37022",
      "iconPrimaryColor": "#ffffff",
      "iconPrimaryDangerColor": "#ffffff",
      "iconPrimaryDangerDisabledColor": "#ffffff",
      "iconPrimaryDangerFocusedColor": "#ffffff",
      "iconPrimaryDangerHoverColor": "#ffffff",
      "iconPrimaryDangerPressedColor": "#ffffff",
      "iconPrimaryDisabledColor": "#ffffff",
      "iconPrimaryFocusedColor": "#ffffff",
      "iconPrimaryGhostColor": "#f37022",
      "iconPrimaryGhostDangerColor": "#ff4d4f",
      "iconPrimaryGhostDangerDisabledColor": "rgba(0, 0, 0, 0.25)",
      "iconPrimaryGhostDangerFocusedColor": "#FF7875",
      "iconPrimaryGhostDangerHoverColor": "#FF7875",
      "iconPrimaryGhostDangerPressedColor": "#D9363E",
      "iconPrimaryGhostDisabledColor": "rgba(0, 0, 0, 0.25)",
      "iconPrimaryGhostFocusedColor": "#FF944D",
      "iconPrimaryGhostHoverColor": "#FF944D",
      "iconPrimaryGhostPressedColor": "#cc5012",
      "iconPrimaryHoverColor": "#ffffff",
      "iconPrimaryPressedColor": "#ffffff",
      "iconSize": 16,
      "iconSizeLG": 24,
      "iconSizeSM": 14,
      "iconTextColor": "rgba(0, 0, 0, 0.65)",
      "iconTextDangerColor": "#ff4d4f",
      "iconTextDangerDisabledColor": "rgba(0, 0, 0, 0.25)",
      "iconTextDangerFocusedColor": "#ff7875",
      "iconTextDangerHoverColor": "#ff7875",
      "iconTextDangerPressedColor": "#f5222d",
      "iconTextDisabledColor": "rgba(0, 0, 0, 0.25)",
      "iconTextFocusedColor": "rgba(0, 0, 0, 0.65)",
      "iconTextHoverColor": "rgba(0, 0, 0, 0.65)",
      "iconTextPressedColor": "rgba(0, 0, 0, 0.65)",
      "lineWidth": 1,
      "lineWidthFocus": 4,
      "linkBg": "rgba(0, 0, 0, 0)",
      "linkBorderColor": "rgba(0, 0, 0, 0)",
      "linkColor": "#f37022",
      "linkDangerBg": "rgba(0, 0, 0, 0)",
      "linkDangerBorderColor": "rgba(0, 0, 0, 0)",
      "linkDangerColor": "#ff4d4f",
      "linkDangerDisabledBg": "rgba(0, 0, 0, 0)",
      "linkDangerDisabledBorderColor": "rgba(0, 0, 0, 0)",
      "linkDangerDisabledColor": "#ffa39e",
      "linkDangerFocusedBg": "rgba(0, 0, 0, 0)",
      "linkDangerFocusedBorderColor": "rgba(0, 0, 0, 0)",
      "linkDangerFocusedColor": "#ff7875",
      "linkDangerHoverBg": "rgba(0, 0, 0, 0)",
      "linkDangerHoverBorderColor": "rgba(0, 0, 0, 0)",
      "linkDangerHoverColor": "#ff7875",
      "linkDangerPressedBg": "rgba(0, 0, 0, 0)",
      "linkDangerPressedBorderColor": "rgba(0, 0, 0, 0)",
      "linkDangerPressedColor": "#f5222d",
      "linkDisabledBg": "rgba(0, 0, 0, 0)",
      "linkDisabledBorderColor": "rgba(0, 0, 0, 0)",
      "linkDisabledColor": "#ffb175",
      "linkFocusedBg": "rgba(0, 0, 0, 0)",
      "linkFocusedBorderColor": "rgba(0, 0, 0, 0)",
      "linkFocusedColor": "#ff944d",
      "linkHoverBg": "rgba(0, 0, 0, 0)",
      "linkHoverBorderColor": "rgba(0, 0, 0, 0)",
      "linkHoverColor": "#ff944d",
      "linkPressedBg": "rgba(0, 0, 0, 0)",
      "linkPressedBorderColor": "rgba(0, 0, 0, 0)",
      "linkPressedColor": "#f37022",
      "marginXS": 8,
      "onlyIconSize": 16,
      "onlyIconSizeLG": 24,
      "onlyIconSizeSM": 14,
      "paddingContentHorizontal": 16,
      "paddingInline": 15,
      "paddingInlineLG": 15,
      "paddingInlineSM": 7,
      "paddingXS": 8,
      "primaryBg": "#f37022",
      "primaryBorderColor": "#f37022",
      "primaryColor": "#ffffff",
      "primaryDangerBg": "#ff4d4f",
      "primaryDangerBorderColor": "#ff4d4f",
      "primaryDangerColor": "#ffffff",
      "primaryDangerDisabledBg": "#ffa39e",
      "primaryDangerDisabledBorderColor": "#ffa39e",
      "primaryDangerDisabledColor": "#ffffff",
      "primaryDangerFocusedBg": "#ff7875",
      "primaryDangerFocusedBorderColor": "#ff7875",
      "primaryDangerFocusedColor": "#ffffff",
      "primaryDangerHoverBg": "#ff7875",
      "primaryDangerHoverBorderColor": "#ff7875",
      "primaryDangerHoverColor": "#ffffff",
      "primaryDangerPressedBg": "#f5222d",
      "primaryDangerPressedBorderColor": "#f5222d",
      "primaryDangerPressedColor": "#ffffff",
      "primaryDisabledBg": "#ffb175",
      "primaryDisabledBorderColor": "#ffb175",
      "primaryDisabledColor": "#ffffff",
      "primaryFocusedBg": "#ff944d",
      "primaryFocusedBorderColor": "#ff944d",
      "primaryFocusedColor": "#ffffff",
      "primaryGhostBg": "rgba(0, 0, 0, 0)",
      "primaryGhostBorderColor": "#f37022",
      "primaryGhostColor": "#f37022",
      "primaryGhostDangerBg": "rgba(0, 0, 0, 0)",
      "primaryGhostDangerBorderColor": "#ff7875",
      "primaryGhostDangerColor": "#ff4d4f",
      "primaryGhostDangerDisabledBg": "rgba(0, 0, 0, 0)",
      "primaryGhostDangerDisabledBorderColor": "#d9d9d9",
      "primaryGhostDangerDisabledColor": "rgba(0, 0, 0, 0.25)",
      "primaryGhostDangerFocusedBg": "rgba(0, 0, 0, 0)",
      "primaryGhostDangerFocusedBorderColor": "#FF7875",
      "primaryGhostDangerFocusedColor": "#FF7875",
      "primaryGhostDangerHoverBg": "rgba(0, 0, 0, 0)",
      "primaryGhostDangerHoverBorderColor": "#FF7875",
      "primaryGhostDangerHoverColor": "#FF7875",
      "primaryGhostDangerPressedBg": "rgba(0, 0, 0, 0)",
      "primaryGhostDangerPressedBorderColor": "#D9363E",
      "primaryGhostDangerPressedColor": "#D9363E",
      "primaryGhostDisabledBg": "rgba(0, 0, 0, 0)",
      "primaryGhostDisabledBorderColor": "rgba(0, 0, 0, 0.25)",
      "primaryGhostDisabledColor": "rgba(0, 0, 0, 0.25)",
      "primaryGhostFocusedBg": "rgba(0, 0, 0, 0)",
      "primaryGhostFocusedBorderColor": "#FF944D",
      "primaryGhostFocusedColor": "#FF944D",
      "primaryGhostHoverBg": "rgba(0, 0, 0, 0)",
      "primaryGhostHoverBorderColor": "#FF944D",
      "primaryGhostHoverColor": "#FF944D",
      "primaryGhostPressedBg": "rgba(0, 0, 0, 0)",
      "primaryGhostPressedBorderColor": "#cc5012",
      "primaryGhostPressedColor": "#cc5012",
      "primaryHoverBg": "#ff944d",
      "primaryHoverBorderColor": "#ff944d",
      "primaryHoverColor": "#ffffff",
      "primaryPressedBg": "#cc5012",
      "primaryPressedBorderColor": "#cc5012",
      "primaryPressedColor": "#ffffff",
      "textBg": "rgba(0, 0, 0, 0)",
      "textBorderColor": "rgba(0, 0, 0, 0)",
      "textColor": "rgba(0, 0, 0, 0.88)",
      "textDangerBg": "rgba(0, 0, 0, 0)",
      "textDangerBorderColor": "rgba(0, 0, 0, 0)",
      "textDangerColor": "#ff4d4f",
      "textDangerDisabledBg": "rgba(0, 0, 0, 0)",
      "textDangerDisabledBorderColor": "rgba(0, 0, 0, 0)",
      "textDangerDisabledColor": "rgba(0, 0, 0, 0.25)",
      "textDangerFocusedBg": "rgba(255, 77, 79, 0.06)",
      "textDangerFocusedBorderColor": "rgba(0, 0, 0, 0)",
      "textDangerFocusedColor": "#ff7875",
      "textDangerHoverBg": "rgba(255, 77, 79, 0.06)",
      "textDangerHoverBorderColor": "rgba(0, 0, 0, 0)",
      "textDangerHoverColor": "#ff7875",
      "textDangerPressedBg": "rgba(255, 77, 79, 0.15)",
      "textDangerPressedBorderColor": "rgba(0, 0, 0, 0)",
      "textDangerPressedColor": "#f5222d",
      "textDisabledBg": "rgba(0, 0, 0, 0)",
      "textDisabledBorderColor": "rgba(0, 0, 0, 0)",
      "textDisabledColor": "rgba(0, 0, 0, 0.25)",
      "textFocusedBg": "rgba(0, 0, 0, 0.06)",
      "textFocusedBorderColor": "rgba(0, 0, 0, 0)",
      "textFocusedColor": "rgba(0, 0, 0, 0.88)",
      "textHoverBg": "rgba(0, 0, 0, 0.06)",
      "textHoverBorderColor": "rgba(0, 0, 0, 0)",
      "textHoverColor": "rgba(0, 0, 0, 0.88)",
      "textPressedBg": "rgba(0, 0, 0, 0.15)",
      "textPressedBorderColor": "rgba(0, 0, 0, 0)",
      "textPressedColor": "rgba(0, 0, 0, 0.88)"
    },
    "Badge": {
      "statusSize": 6,
      "indicatorHeight": 20,
      "dotSize": 6,
      "paddingXS": 8,
      "marginXS": 8,
      "lineWidth": 1,
      "borderRadiusSM": 4,
      "fontSizeSM": 14,
      "fontSize": 14,
      "colorWarning": "#faad14",
      "colorTextPlaceholder": "rgba(0, 0, 0, 0.25)",
      "colorTextLightSolid": "#ffffff",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSuccess": "#52c41a",
      "colorPrimary": "#f37022",
      "colorErrorHover": "#ff7875",
      "colorError": "#ff4d4f",
      "colorBorderBg": "#ffffff",
      "colorBgContainer": "#ffffff",
      "indicatorHeightSM": 14,
      "textFontSize": 14,
      "textFontSizeSM": 14,
      "fontHeight": 22,
      "lineHeight": 1.2,
      "fontFamily": "Inter",
      "dangerIndicatorBg": "#fe6963",
      "primaryIndicatorBg": "#f37022",
      "defaultIndicatorBg": "#f0f0f0",
      "primaryTextColor": "#ffffff",
      "defaultTextColor": "#1f1f1f",
      "dangerTextColor": "#ffffff"
    },
    "Form": {
      "screenXSMax": 575,
      "screenSMMax": 767,
      "screenMDMax": 991,
      "screenLGMax": 1199,
      "paddingXS": 8,
      "paddingSM": 12,
      "marginXXS": 4,
      "marginXS": 8,
      "marginLG": 24,
      "margin": 16,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSizeLG": 16,
      "fontSize": 14,
      "controlOutlineWidth": 2,
      "controlOutline": "rgba(243, 112, 34, 0.1)",
      "controlHeightSM": 24,
      "controlHeightLG": 40,
      "controlHeight": 32,
      "colorWarning": "#faad14",
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorTextDescription": "#ff4d4f",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSuccess": "#52c41a",
      "colorPrimary": "#f37022",
      "colorError": "#ff4d4f",
      "colorBorder": "#d9d9d9",
      "labelRequiredMarkColor": "#ff4d4f",
      "labelColor": "rgba(0, 0, 0, 0.88)",
      "itemMarginBottom": 24,
      "labelColonMarginInlineEnd": 8,
      "labelColonMarginInlineStart": 2,
      "labelHeight": 32,
      "labelFontSize": 14,
      "fontFamily": "Inter"
    },
    "Avatar": {
      "marginXXS": 4,
      "marginXS": 8,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSizeXL": 20,
      "fontSizeLG": 16,
      "fontSizeHeading3": 24,
      "fontSize": 14,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "borderRadius": 6,
      "colorTextPlaceholder": "rgba(0, 0, 0, 0.25)",
      "colorTextLightSolid": "#ffffff",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorBorderBg": "#ffffff",
      "containerSizeSM": 24,
      "containerSizeLG": 40,
      "containerSize": 32,
      "textFontSize": 18,
      "textFontSizeLG": 24,
      "textFontSizeSM": 14,
      "fontFamily": "Inter"
    },
    "Tour": {
      "sizePopupArrow": 16,
      "paddingXS": 8,
      "padding": 16,
      "marginXS": 8,
      "lineHeight": 1.2,
      "fontWeightStrong": 600,
      "fontSize": 14,
      "borderRadiusXS": 2,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "borderRadius": 6,
      "colorWhite": "#ffffff",
      "colorTextLightSolid": "#ffffff",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimary": "#f37022",
      "colorIconHover": "rgba(0, 0, 0, 0.88)",
      "colorIcon": "rgba(0, 0, 0, 0.45)",
      "colorFill": "rgba(0, 0, 0, 0.15)",
      "colorBgTextHover": "rgba(0, 0, 0, 0.06)",
      "colorBgElevated": "#ffffff",
      "closeBtnSize": 22,
      "primaryNextBtnHoverBg": "#f0f0f0",
      "primaryPrevBtnBg": "rgba(255, 255, 255, 0.15)",
      "fontFamily": "Inter",
      "lineWidthFocus": 4
    },
    "QRCode": {
      "paddingSM": 12,
      "marginXS": 8,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSize": 14,
      "controlHeight": 32,
      "borderRadiusLG": 8,
      "colorWhite": "#ffffff",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "fontFamily": "Inter"
    },
    "Upload": {
      "paddingXS": 8,
      "paddingSM": 12,
      "padding": 16,
      "marginXXS": 4,
      "marginXS": 8,
      "marginXL": 32,
      "margin": 16,
      "lineWidth": 1,
      "lineHeight": 1.375,
      "fontSizeLG": 16,
      "fontSizeHeading3": 24,
      "fontSizeHeading2": 30,
      "fontSize": 14,
      "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
      "controlHeightLG": 40,
      "borderRadiusLG": 8,
      "colorTextLightSolid": "#ffffff",
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimary": "#f37022",
      "colorFillAlter": "rgba(0, 0, 0, 0.02)",
      "colorErrorBg": "#fff2f0",
      "colorError": "#ff4d4f",
      "colorBorder": "#d9d9d9",
      "colorBgMask": "rgba(0, 0, 0, 0.45)",
      "fontHeight": 22,
      "fontHeightSM": 20,
      "lineWidthFocus": 4,
      "fontFamily": "Inter",
      "controlItemBgError": "#fff1f0"
    },
    "Typography": {
      "paddingSM": 12,
      "marginXXS": 4,
      "marginXS": 8,
      "lineWidth": 1,
      "lineHeightHeading5": 1.5,
      "lineHeightHeading4": 1.4,
      "lineHeightHeading3": 1.3333333333333333,
      "lineHeightHeading2": 1.2666666666666666,
      "lineHeightHeading1": 1.2105263157894737,
      "lineHeight": 1.5714285714285714,
      "fontWeightStrong": 600,
      "fontSizeHeading5": 16,
      "fontSizeHeading4": 20,
      "fontSizeHeading3": 24,
      "fontSizeHeading2": 30,
      "fontSizeHeading1": 38,
      "fontSize": 14,
      "colorWarning": "#faad14",
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSuccess": "#52c41a",
      "colorLinkHover": "#ff944d",
      "colorLinkActive": "#cc5012",
      "colorLink": "#f37022",
      "colorErrorHover": "#ff7875",
      "colorErrorActive": "#d9363e",
      "colorError": "#ff4d4f",
      "fontFamilyCode": "Courier Prime"
    },
    "TreeSelect": {
      "paddingXS": 8,
      "marginXXS": 4,
      "marginXS": 8,
      "lineWidthFocus": 4,
      "lineWidthBold": 2,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSizeLG": 16,
      "fontSize": 14,
      "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
      "controlItemBgActive": "#fff8f0",
      "controlInteractiveSize": 16,
      "controlHeightSM": 24,
      "borderRadiusSM": 4,
      "borderRadius": 6,
      "colorWhite": "#ffffff",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimaryBorder": "#ffcb9e",
      "colorPrimary": "#f37022",
      "colorBorder": "#d9d9d9",
      "colorBgElevated": "#ffffff",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "colorBgContainer": "#ffffff",
      "titleHeight": 24,
      "nodeSelectedBg": "#fff8f0",
      "nodeHoverBg": "rgba(0, 0, 0, 0.04)",
      "fontFamily": "Inter",
      "iconSize": 16,
      "menuItemPaddingHorizontal": 4,
      "menuItemPaddingVertical": 5,
      "subtextFontSize": 13,
      "menuItemDefaultColor": "#1f1f1f",
      "menuItemSubtleColor": "#a6a6a6",
      "menuMaxHeight": 294,
      "inputMaxHeightSM": 105,
      "inputMaxHeight": 145,
      "inputMaxHeightLG": 185,
      "multipleItemMaxWidth": 150
    },
    "Tree": {
      "paddingSM": 12,
      "borderRadiusLG": 8,
      "paddingXS": 8,
      "marginXXS": 4,
      "marginXS": 8,
      "lineWidthFocus": 4,
      "lineWidthBold": 2,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSizeLG": 16,
      "fontSize": 14,
      "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
      "controlItemBgActive": "#fff8f0",
      "controlInteractiveSize": 16,
      "controlHeightSM": 24,
      "borderRadiusSM": 4,
      "borderRadius": 6,
      "colorWhite": "#ffffff",
      "colorTextLightSolid": "#ffffff",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimaryBorder": "#ffcb9e",
      "colorPrimary": "#f37022",
      "colorBorder": "#d9d9d9",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "colorBgContainer": "#ffffff",
      "titleHeight": 24,
      "titleHeightLg": 40,
      "nodeSelectedBg": "#fff8f0",
      "nodeHoverBg": "rgba(0, 0, 0, 0.04)",
      "directoryNodeSelectedColor": "#ffffff",
      "directoryNodeSelectedBg": "#f37022",
      "fontFamily": "Inter"
    },
    "Tag": {
      "paddingXXS": 4,
      "marginXS": 8,
      "lineWidth": 1,
      "lineHeightSM": 1.4,
      "fontSizeSM": 14,
      "fontSizeIcon": 12,
      "fontSize": 14,
      "borderRadiusSM": 4,
      "colorTextLightSolid": "#ffffff",
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimaryActive": "#cc5012",
      "colorPrimary": "#f37022",
      "colorFillTertiary": "rgba(0, 0, 0, 0.04)",
      "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
      "colorFillQuaternary": "rgba(0, 0, 0, 0.02)",
      "fontFamily": "Inter",
      "statusDefaultBg": "rgba(0, 0, 0, 0.02)",
      "statusDefaultBorder": "#d9d9d9",
      "statusDefaultText": "rgba(0, 0, 0, 0.88)",
      "statusErrorBg": "#fff1f0",
      "statusErrorBorder": "#ffccc7",
      "statusErrorText": "#ff4d4f",
      "statusProcessingBg": "#e6f4ff",
      "statusProcessingBorder": "#91caff",
      "statusProcessingText": "#1677ff",
      "statusWarningBg": "#fffbe6",
      "statusWarningBorder": "#ffe58f",
      "statusWarningText": "#d48806",
      "statusSuccessBg": "#f6ffed",
      "statusSuccessBorder": "#b7eb8f",
      "statusSuccessText": "#389e0d",
      "colorfulMagentaText": "#eb2f96",
      "colorfulMagentaBg": "#fff0f6",
      "colorfulMagentaBorder": "#ffadd2",
      "colorfulRedText": "#f5222d",
      "colorfulRedBg": "#fff1f0",
      "colorfulRedBorder": "#ffa39e",
      "colorfulVolcanoText": "#fa541c",
      "colorfulVolcanoBg": "#fff2e8",
      "colorfulVolcanoBorder": "#ffbb96",
      "colorfulOrangeText": "#f37022",
      "colorfulOrangeBg": "#fff8f0",
      "colorfulOrangeBorder": "#ffcb9e",
      "colorfulGoldText": "#d48806",
      "colorfulGoldBg": "#fffbe6",
      "colorfulGoldBorder": "#ffe58f",
      "colorfulLimeText": "#7cb305",
      "colorfulLimeBg": "#fcffe6",
      "colorfulLimeBorder": "#eaff8f",
      "colorfulGreenText": "#389e0d",
      "colorfulGreenBg": "#f6ffed",
      "colorfulGreenBorder": "#b7eb8f",
      "colorfulCyanText": "#08979c",
      "colorfulCyanBg": "#e6fffb",
      "colorfulCyanBorder": "#87e8de",
      "colorfulBlueText": "#1677ff",
      "colorfulBlueBg": "#e6f4ff",
      "colorfulBlueBorder": "#91caff",
      "colorfulGeekblueText": "#2f54eb",
      "colorfulGeekblueBg": "#f0f5ff",
      "colorfulGeekblueBorder": "#adc6ff",
      "colorfulPurpleText": "#722ed1",
      "colorfulPurpleBg": "#f9f0ff",
      "colorfulPurpleBorder": "#d3adf7"
    },
    "Filter": {
      "controlMaxWidth": 450
    },
    "Statistic": {
      "padding": 16,
      "marginXXS": 4,
      "lineHeight": 1.2,
      "fontSizeHeading3": 24,
      "fontSize": 14,
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "contentFontSize": 24,
      "titleFontSize": 14,
      "fontFamily": "Inter"
    },
    "Skeleton": {
      "padding": 16,
      "marginXXS": 4,
      "marginSM": 12,
      "marginLG": 24,
      "controlHeightXS": 16,
      "controlHeightSM": 24,
      "controlHeightLG": 40,
      "controlHeight": 32,
      "borderRadiusSM": 4,
      "colorFillContent": "rgba(0, 0, 0, 0.06)",
      "colorFill": "rgba(0, 0, 0, 0.15)"
    },
    "Select": {
      "paddingXXS": 4,
      "paddingXS": 8,
      "paddingSM": 12,
      "lineWidth": 1,
      "lineHeight": 1.5714285714285714,
      "fontWeightStrong": 600,
      "fontSizeSM": 12,
      "fontSizeLG": 16,
      "fontSizeIcon": 16,
      "fontSize": 14,
      "controlPaddingHorizontalSM": 8,
      "controlPaddingHorizontal": 12,
      "controlOutlineWidth": 2,
      "controlOutline": "rgba(243, 112, 34, 0.1)",
      "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
      "controlItemBgActive": "#ffffff",
      "controlHeightXS": 16,
      "controlHeightSM": 24,
      "controlHeightLG": 40,
      "controlHeight": 32,
      "borderRadiusXS": 2,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "borderRadius": 6,
      "colorWarningOutline": "rgba(255, 215, 5, 0.1)",
      "colorWarningHover": "#ffd666",
      "colorTextTertiary": "rgba(0, 0, 0, 0.45)",
      "colorTextQuaternary": "rgba(0, 0, 0, 0.25)",
      "colorTextPlaceholder": "rgba(0, 0, 0, 0.25)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimary": "#f37022",
      "colorIconHover": "rgba(0, 0, 0, 0.88)",
      "colorIcon": "rgba(0, 0, 0, 0.45)",
      "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
      "colorErrorOutline": "rgba(255, 38, 6, 0.06)",
      "colorErrorHover": "#ff7875",
      "colorBorder": "#d9d9d9",
      "colorBgElevated": "#ffffff",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "colorBgContainer": "#ffffff",
      "hoverBorderColor": "#ff944d",
      "singleItemHeightLG": 40,
      "selectorBg": "#ffffff",
      "optionSelectedColor": "rgba(0, 0, 0, 0.88)",
      "optionSelectedBg": "#ffffff",
      "optionLineHeight": 1.5714285714285714,
      "optionHeight": 32,
      "optionActiveBg": "rgba(0, 0, 0, 0.04)",
      "optionFontSize": 14,
      "optionSelectedFontWeight": 600,
      "optionFontSizeIcon": 16,
      "multipleSelectorBgDisabled": "rgba(0, 0, 0, 0.04)",
      "multipleItemHeightLG": 32,
      "multipleItemHeight": 24,
      "multipleItemColorDisabled": "rgba(0, 0, 0, 0.25)",
      "multipleItemBorderColorDisabled": "rgba(0, 0, 0, 0)",
      "multipleItemBorderColor": "rgba(0, 0, 0, 0)",
      "multipleItemBg": "rgba(0, 0, 0, 0.06)",
      "clearBg": "#ffffff",
      "fontFamily": "Inter",
      "subtextFontSize": 13,
      "menuItemSubtleColor": "rgba(0, 0, 0, 0.45)",
      "menuItemDefaultColor": "rgba(0, 0, 0, 0.88)",
      "customValueDescriptionColor": "rgba(0, 0, 0, 0.45)",
      "customValueDefaultColor": "rgba(0, 0, 0, 0.88)",
      "menuMaxHeight": 294,
      "inputMaxHeightSM": 105,
      "inputMaxHeight": 145,
      "inputMaxHeightLG": 185,
      "multipleItemMaxWidth": 150,
      "selectIconSize": 16,
      "selectBg": "rgba(0, 0, 0, 0.02)",
      "selectIconColor": "rgba(0, 0, 0, 0.65)",
      "selectMenuIconColor": "rgba(0, 0, 0, 0.65)",
      "selectMenuIconActiveColor": "#1f1f1f",
      "selectMenuIconSize": 16
    },
    "Result": {
      "paddingXS": 8,
      "paddingXL": 32,
      "paddingLG": 24,
      "padding": 16,
      "marginXS": 8,
      "lineHeightHeading3": 32,
      "lineHeight": 1.2,
      "fontSizeHeading3": 24,
      "fontSize": 14,
      "colorWarning": "#faad14",
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorSuccess": "#52c41a",
      "colorInfo": "#f37022",
      "colorFillAlter": "rgba(0, 0, 0, 0.02)",
      "colorError": "#ff4d4f",
      "iconFontSize": 72,
      "subtitleFontSize": 14,
      "titleFontSize": 24
    },
    "Progress": {
      "paddingXS": 8,
      "marginXXS": 4,
      "marginXS": 8,
      "lineHeight": 1.2,
      "fontSizeSM": 12,
      "fontSize": 14,
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSuccess": "#52c41a",
      "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
      "colorError": "#ff4d4f",
      "colorBgContainer": "#ffffff",
      "remainingColor": "rgba(0, 0, 0, 0.06)",
      "defaultColor": "#f37022",
      "circleTextColor": "rgba(0, 0, 0, 0.88)",
      "fontFamily": "Inter"
    },
    "Popconfirm": {
      "marginXXS": 4,
      "marginXS": 8,
      "fontWeightStrong": 600,
      "fontSize": 14,
      "colorWarning": "#faad14",
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorText": "rgba(0, 0, 0, 0.88)"
    },
    "Pagination": {
      "screenSM": 576,
      "screenLG": 992,
      "paddingXXS": 4,
      "paddingSM": 12,
      "marginXXS": 4,
      "marginXS": 8,
      "marginSM": 12,
      "margin": 16,
      "lineWidthFocus": 4,
      "lineWidth": 1,
      "lineHeightLG": 1.4,
      "lineHeight": 1.2,
      "fontWeightStrong": 600,
      "fontSizeSM": 12,
      "fontSizeLG": 16,
      "fontSize": 14,
      "controlPaddingHorizontalSM": 8,
      "controlPaddingHorizontal": 12,
      "controlOutlineWidth": 2,
      "controlOutline": "rgba(243, 112, 34, 0.1)",
      "controlItemBgActiveDisabled": "rgba(0, 0, 0, 0.15)",
      "controlHeightSM": 24,
      "controlHeightLG": 40,
      "controlHeight": 32,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "borderRadius": 6,
      "colorWarningOutline": "rgba(255, 215, 5, 0.1)",
      "colorTextPlaceholder": "rgba(0, 0, 0, 0.25)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimaryBorder": "#ffcb9e",
      "colorPrimary": "#f37022",
      "colorFillAlter": "rgba(0, 0, 0, 0.02)",
      "colorErrorOutline": "rgba(255, 38, 6, 0.06)",
      "colorBorder": "#d9d9d9",
      "colorBgTextHover": "rgba(0, 0, 0, 0.06)",
      "colorBgTextActive": "rgba(0, 0, 0, 0.15)",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "colorBgContainer": "#ffffff",
      "itemSizeSM": 24,
      "itemSize": 32,
      "itemLinkBg": "#ffffff",
      "itemInputBg": "#ffffff",
      "itemBg": "#ffffff",
      "itemActiveColorDisabled": "rgba(0, 0, 0, 0.25)",
      "itemActiveBgDisabled": "rgba(0, 0, 0, 0.15)",
      "itemActiveBg": "#ffffff",
      "fontFamily": "Inter"
    },
    "Modal": {
      "screenSMMax": 767,
      "paddingXS": 8,
      "paddingMD": 20,
      "paddingLG": 24,
      "paddingContentHorizontalLG": 24,
      "padding": 16,
      "marginXS": 8,
      "marginSM": 12,
      "marginLG": 24,
      "margin": 16,
      "lineWidthFocus": 4,
      "lineWidth": 1,
      "lineHeightHeading5": 1.4,
      "lineHeight": 1.375,
      "fontWeightStrong": 600,
      "fontSizeLG": 16,
      "fontSizeHeading5": 16,
      "fontSize": 14,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "colorWarning": "#faad14",
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSuccess": "#52c41a",
      "colorPrimaryBorder": "#ffcb9e",
      "colorIconHover": "rgba(0, 0, 0, 0.88)",
      "colorIcon": "rgba(0, 0, 0, 0.45)",
      "colorBgMask": "rgba(0, 0, 0, 0.45)",
      "titleColor": "rgba(0, 0, 0, 0.88)",
      "headerBg": "#ffffff",
      "footerBg": "rgba(0, 0, 0, 0)",
      "contentBg": "#ffffff",
      "titleFontSize": 16,
      "titleLineHeight": 1.375,
      "fontFamily": "Inter",
      "iconInfoColor": "rgba(0, 0, 0, 0.3)",
      "iconErrorColor": "#ff4d4f",
      "iconSuccessColor": "#52c41a",
      "iconWarningColor": "#faad14",
      "iconSize": 32,
      "closeIconSize": 16
    },
    "Message": {
      "paddingXS": 8,
      "paddingSM": 12,
      "marginXS": 8,
      "lineHeight": 1.2,
      "fontSizeLG": 16,
      "fontSize": 14,
      "controlHeightLG": 40,
      "borderRadiusLG": 8,
      "colorWarning": "#faad14",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSuccess": "#52c41a",
      "colorInfo": "#f37022",
      "colorError": "#ff4d4f",
      "contentBg": "#ffffff",
      "fontFamily": "Inter"
    },
    "List": {
      "screenSM": 576,
      "screenMD": 768,
      "paddingXS": 8,
      "paddingSM": 12,
      "paddingLG": 24,
      "paddingContentVerticalSM": 8,
      "paddingContentVerticalLG": 16,
      "paddingContentVertical": 12,
      "paddingContentHorizontalLG": 24,
      "paddingContentHorizontal": 16,
      "padding": 16,
      "marginXXS": 4,
      "marginXXL": 48,
      "marginSM": 12,
      "marginLG": 24,
      "margin": 16,
      "lineWidth": 1,
      "lineHeightLG": 1.4,
      "lineHeight": 1.2,
      "fontSizeSM": 12,
      "fontSizeLG": 16,
      "fontSize": 14,
      "controlHeightLG": 40,
      "controlHeight": 32,
      "borderRadiusLG": 8,
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "colorPrimary": "#f37022",
      "colorBorder": "#d9d9d9",
      "headerBg": "rgba(0, 0, 0, 0)",
      "footerBg": "rgba(0, 0, 0, 0)",
      "avatarMarginRight": 16,
      "descriptionFontSize": 14,
      "fontFamily": "Inter"
    },
    "FloatButton": {
      "paddingXXS": 4,
      "marginXXL": 48,
      "marginLG": 24,
      "margin": 16,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSizeSM": 12,
      "fontSizeLG": 16,
      "fontSizeIcon": 12,
      "fontSize": 14,
      "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
      "controlHeightLG": 40,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "colorTextLightSolid": "#ffffff",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimary": "#f37022",
      "colorFillContent": "rgba(0, 0, 0, 0.06)",
      "colorBgElevated": "#ffffff",
      "fontFamily": "Inter"
    },
    "Empty": {
      "borderRadiusSM": 3,
      "colorBgContainer": "#ffffff",
      "colorBgContainerDisabled": "#ffffff",
      "colorBorder": "#d9d9d9",
      "colorPrimary": "#f37022",
      "colorPrimaryBorder": "#ffcb9e",
      "colorPrimaryHover": "#ff944d",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorWhite": "#ffffff",
      "controlInteractiveSize": 16,
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontSizeLG": 16,
      "lineHeight": 1.2,
      "lineWidth": 1,
      "lineWidthBold": 2,
      "lineWidthFocus": 4,
      "marginXS": 8,
      "paddingXS": 8
    },
    "Dropdown": {
      "sizePopupArrow": 16,
      "paddingXXS": 4,
      "paddingXS": 8,
      "marginXXS": 4,
      "marginXS": 8,
      "lineWidthFocus": 4,
      "lineHeight": 1.2,
      "fontSizeSM": 12,
      "fontSizeIcon": 12,
      "fontSize": 14,
      "controlPaddingHorizontal": 12,
      "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
      "controlItemBgActiveHover": "#ffe3c7",
      "controlItemBgActive": "#fff8f0",
      "controlHeight": 32,
      "borderRadiusXS": 2,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "colorTextLightSolid": "#ffffff",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "colorPrimaryBorder": "#ffcb9e",
      "colorPrimary": "#f37022",
      "colorError": "#ff4d4f",
      "colorBgElevated": "#ffffff",
      "paddingBlock": 5,
      "fontFamily": "Inter"
    },
    "Drawer": {
      "paddingXS": 8,
      "paddingLG": 24,
      "padding": 16,
      "marginSM": 12,
      "lineWidth": 1,
      "lineHeightLG": 1.4,
      "fontWeightStrong": 600,
      "fontSizeLG": 16,
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "colorIconHover": "rgba(0, 0, 0, 0.88)",
      "colorIcon": "rgba(0, 0, 0, 0.45)",
      "colorBgMask": "rgba(0, 0, 0, 0.45)",
      "colorBgElevated": "#ffffff",
      "lineWidthFocus": 4,
      "width": 500,
      "widthLG": 800,
      "widthSM": 350,
      "height": 450,
      "heightSM": 300,
      "heightLG": 600,
      "maxWidth": 1000,
      "maxWidthSM": 800,
      "maxWidthLG": 600,
      "maxHeight": 900,
      "maxHeightSM": 600,
      "maxHeightLG": 1200,
      "minWidth": 250,
      "minWidthSM": 200,
      "minWidthLG": 400,
      "minHeight": 250,
      "minHeightSM": 300,
      "minHeightLG": 300,
      "resizerWidth": 8,
      "resizerBg": "#f0f0f0",
      "resizerGutterBg": "rgba(0, 0, 0, 0.15)",
      "resizerGutterHeight": 28,
      "resizerGutterWidth": 2,
      "resizerGutterBorderRadius": 1,
      "iconSize": 20
    },
    "Divider": {
      "marginXS": 8,
      "marginLG": 24,
      "margin": 16,
      "lineWidth": 1,
      "fontSizeLG": 16,
      "fontSize": 14,
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "lineHeight": 1.2,
      "fontFamily": "Inter"
    },
    "Descriptions": {
      "paddingXS": 8,
      "paddingSM": 12,
      "paddingLG": 24,
      "padding": 16,
      "marginXXS": 4,
      "marginXS": 8,
      "lineWidth": 1,
      "lineHeightSM": 20,
      "lineHeightLG": 1.4,
      "lineHeight": 1.2,
      "fontWeightStrong": 600,
      "fontSizeSM": 12,
      "fontSizeLG": 16,
      "fontSize": 14,
      "borderRadiusLG": 8,
      "colorTextTertiary": "rgba(0, 0, 0, 0.45)",
      "colorTextSecondary": "rgba(0, 0, 0, 0.65)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "colorFillAlter": "rgba(0, 0, 0, 0.02)",
      "titleColor": "rgba(0, 0, 0, 0.88)",
      "labelBg": "rgba(0, 0, 0, 0.02)",
      "contentColor": "rgba(0, 0, 0, 0.88)",
      "fontFamily": "Inter"
    },
    "DatePicker": {
      "sizePopupArrow": 16,
      "paddingXXS": 4,
      "paddingXS": 8,
      "paddingSM": 12,
      "padding": 16,
      "marginXXS": 4,
      "marginXS": 8,
      "lineWidthBold": 2,
      "lineWidth": 1,
      "lineHeightLG": 1.4,
      "lineHeight": 1.5714285714285714,
      "fontWeightStrong": 600,
      "fontSizeLG": 16,
      "fontSize": 14,
      "controlPaddingHorizontalSM": 8,
      "controlPaddingHorizontal": 12,
      "controlOutlineWidth": 2,
      "controlOutline": "rgba(243, 112, 34, 0.1)",
      "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
      "controlItemBgActive": "#fff8f0",
      "controlHeightSM": 24,
      "controlHeightLG": 40,
      "controlHeight": 32,
      "borderRadiusXS": 2,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "borderRadius": 6,
      "colorWarningOutline": "rgba(255, 215, 5, 0.1)",
      "colorWarningHover": "#ffd666",
      "colorWarning": "#faad14",
      "colorTextQuaternary": "rgba(0, 0, 0, 0.25)",
      "colorTextPlaceholder": "rgba(0, 0, 0, 0.25)",
      "colorTextLightSolid": "#ffffff",
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimaryBorder": "#ffcb9e",
      "colorPrimary": "#f37022",
      "colorLinkHover": "#ff944d",
      "colorLinkActive": "#cc5012",
      "colorLink": "#f37022",
      "colorIconHover": "rgba(0, 0, 0, 0.88)",
      "colorIcon": "rgba(0, 0, 0, 0.45)",
      "colorFillAlter": "rgba(0, 0, 0, 0.02)",
      "colorErrorOutline": "rgba(255, 38, 6, 0.06)",
      "colorErrorHover": "#ff7875",
      "colorError": "#ff4d4f",
      "colorBorder": "#d9d9d9",
      "colorBgElevated": "#ffffff",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "colorBgContainer": "#ffffff",
      "hoverBorderColor": "#ff944d",
      "cellHoverBg": "rgba(0, 0, 0, 0.04)",
      "cellHeight": 24,
      "activeBorderColor": "#f37022",
      "paddingInline": 11,
      "paddingInlineSM": 7,
      "colorFillTertiary": "rgba(0, 0, 0, 0.04)",
      "colorErrorBg": "#fff2f0",
      "colorWarningBg": "#fffbe6",
      "colorWarningText": "#faad14",
      "colorErrorText": "#ff4d4f",
      "colorWarningBgHover": "#fff1b8",
      "colorErrorBgHover": "#fff1f0",
      "activeBg": "#ffffff",
      "hoverBg": "#ffffff",
      "cellBgDisabled": "rgba(0, 0, 0, 0.04)",
      "cellActiveWithRangeBg": "#fff8f0",
      "cellHoverWithRangeBg": "#c8dfff",
      "cellRangeBorderColor": "#7cb3ff",
      "multipleItemBg": "rgba(0, 0, 0, 0.06)",
      "multipleItemBorderColor": "rgba(0, 0, 0, 0)",
      "multipleItemBorderColorDisabled": "rgba(0, 0, 0, 0)",
      "multipleItemColorDisabled": "rgba(0, 0, 0, 0.25)",
      "multipleSelectorBgDisabled": "rgba(0, 0, 0, 0.04)",
      "cellWidth": 36,
      "multipleItemHeight": 24,
      "multipleItemHeightLG": 32,
      "multipleItemHeightSM": 16,
      "paddingBlock": 4,
      "paddingBlockLG": 7,
      "paddingBlockSM": 0,
      "paddingInline 2": 11,
      "presetsMaxWidth": 200,
      "presetsWidth": 120,
      "textHeight": 40,
      "timeCellHeight": 28,
      "timeColumnHeight": 224,
      "timeColumnWidth": 56,
      "withoutTimeCellHeight": 66,
      "inputFontSize": 14,
      "inputFontSizeLG": 16,
      "inputFontSizeSM": 12,
      "fontHeight": 22,
      "fontHeightLG": 24,
      "fontFamily": "Inter"
    },
    "Collapse": {
      "paddingXXS": 4,
      "paddingXS": 8,
      "paddingSM": 12,
      "paddingLG": 24,
      "padding": 16,
      "marginSM": 12,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSizeLG": 16,
      "fontSizeIcon": 16,
      "fontSize": 14,
      "borderRadiusLG": 8,
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorFillAlter": "rgba(0, 0, 0, 0.02)",
      "colorBorder": "#d9d9d9",
      "colorBgContainer": "#ffffff",
      "headerBg": "rgba(0, 0, 0, 0.02)",
      "contentBg": "#ffffff",
      "fontHeight": 22,
      "fontHeightLG": 24,
      "lineHeightLG": 1.4,
      "fontFamily": "Inter"
    },
    "Checkbox": {
      "paddingXS": 8,
      "marginXS": 8,
      "lineWidthFocus": 4,
      "lineWidthBold": 2,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSizeLG": 16,
      "fontSize": 14,
      "controlInteractiveSize": 16,
      "borderRadiusSM": 4,
      "colorWhite": "#ffffff",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimaryBorder": "#ffcb9e",
      "colorPrimary": "#f37022",
      "colorBorder": "#d9d9d9",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "colorBgContainer": "#ffffff",
      "fontFamily": "Inter"
    },
    "Breadcrumb": {
      "paddingXXS": 4,
      "marginXXS": 4,
      "marginXS": 8,
      "lineWidthFocus": 4,
      "lineHeight": 1.2,
      "fontSizeIcon": 14,
      "fontSize": 14,
      "borderRadiusSM": 4,
      "colorPrimaryBorder": "#ffcb9e",
      "colorBgTextHover": "rgba(0, 0, 0, 0.06)",
      "separatorColor": "rgba(0, 0, 0, 0.45)",
      "linkHoverColor": "rgba(0, 0, 0, 0.88)",
      "linkColor": "rgba(0, 0, 0, 0.45)",
      "lastItemColor": "rgba(0, 0, 0, 0.88)",
      "itemColor": "rgba(0, 0, 0, 0.45)",
      "separatorMargin": 8,
      "iconFontSize": 14,
      "fontHeight": 22,
      "fontFamily": "Inter"
    },
    "Anchor": {
      "paddingXXS": 4,
      "lineWidthBold": 2,
      "lineHeight": 1.2,
      "fontSizeLG": 16,
      "fontSize": 14,
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "colorPrimary": "#f37022",
      "linkPaddingInlineStart": 16,
      "linkPaddingBlock": 4,
      "fontFamily": "Inter"
    },
    "Alert": {
      "paddingMD": 20,
      "paddingContentVerticalSM": 8,
      "paddingContentHorizontalLG": 24,
      "marginXS": 8,
      "marginSM": 12,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "fontSizeLG": 16,
      "fontSizeIcon": 12,
      "fontSizeHeading3": 24,
      "fontSize": 14,
      "borderRadiusLG": 8,
      "colorWarningBorder": "#ffe58f",
      "colorWarningBg": "#fffbe6",
      "colorWarning": "#faad14",
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorSuccessBorder": "#b7eb8f",
      "colorSuccessBg": "#f6ffed",
      "colorSuccess": "#52c41a",
      "colorInfoBorder": "#ffcb9e",
      "colorInfoBg": "#fff8f0",
      "colorInfo": "#f37022",
      "colorIconHover": "rgba(0, 0, 0, 0.88)",
      "colorIcon": "rgba(0, 0, 0, 0.45)",
      "colorErrorBorder": "#ffccc7",
      "colorErrorBg": "#fff2f0",
      "colorError": "#ff4d4f",
      "withDescriptionIconSize": 24,
      "fontFamily": "Inter"
    },
    "Space": {
      "paddingXS": 8,
      "paddingLG": 24,
      "padding": 16
    },
    "AutoComplete": {
      "paddingXXS": 4,
      "paddingXS": 8,
      "paddingSM": 12,
      "lineWidth": 1,
      "lineHeight": 1.2,
      "controlPaddingHorizontalSM": 8,
      "controlPaddingHorizontal": 12,
      "controlOutlineWidth": 2,
      "controlOutline": "rgba(243, 112, 34, 0.1)",
      "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
      "controlItemBgActive": "#fff8f0",
      "controlHeightXS": 16,
      "controlHeightSM": 24,
      "controlHeightLG": 40,
      "controlHeight": 32,
      "borderRadiusXS": 2,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "borderRadius": 6,
      "colorWarningOutline": "rgba(255, 215, 5, 0.1)",
      "colorWarningHover": "#ffd666",
      "colorWarning": "#faad14",
      "colorTextTertiary": "rgba(0, 0, 0, 0.45)",
      "colorTextQuaternary": "rgba(0, 0, 0, 0.25)",
      "colorTextPlaceholder": "rgba(0, 0, 0, 0.25)",
      "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorPrimaryHover": "#ff944d",
      "colorPrimary": "#f37022",
      "colorIconHover": "rgba(0, 0, 0, 0.88)",
      "colorIcon": "rgba(0, 0, 0, 0.45)",
      "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
      "colorErrorOutline": "rgba(255, 38, 6, 0.06)",
      "colorErrorHover": "#ff7875",
      "colorError": "#ff4d4f",
      "colorBorder": "#d9d9d9",
      "colorBgElevated": "#ffffff",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "colorBgContainer": "#ffffff",
      "optionActiveBg": "rgba(0, 0, 0, 0.04)",
      "optionHeight": 32,
      "optionFontSize": 14,
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontSizeIcon": 12,
      "fontSizeLG": 16,
      "fontSizeSM": 12
    },
    "Layout": {
      "bodyBg": "#ffffff",
      "borderRadius": 6,
      "colorText": "rgba(0, 0, 0, 0.88)",
      "fontSize": 14,
      "fontSizeXL": 20,
      "footerBg": "#f5f5f5",
      "headerBg": "#ffffff",
      "headerColor": "rgba(0, 0, 0, 0.88)",
      "headerHeight": 44,
      "lightSiderBg": "#ffffff",
      "lightTriggerBg": "#ffffff",
      "lightTriggerColor": "rgba(0, 0, 0, 0.88)",
      "siderBg": "#212121",
      "triggerBg": "#002140",
      "triggerColor": "#ffffff",
      "triggerHeight": 48,
      "zeroTriggerHeight": 40,
      "zeroTriggerWidth": 40,
      "headerSplitColor": "rgba(0, 0, 0, 0.06)",
      "panelPadding": 24,
      "panelMargin": 16,
      "panelWidth": 300,
      "panelSplitColor": "rgba(0, 0, 0, 0.06)"
    },
    "Mentions": {
      "fontFamily": "Inter",
      "fontSize": 14,
      "lineHeight": 1.2
    },
    "Icon": {
      "defaultColor": "rgba(0, 0, 0, 0.65)",
      "primaryColor": "#f37022"
    }
  }
}
;

export default _default;
