import { Meta, StoryFn } from '@storybook/react';
import { NButton } from '../models';
declare const meta: Meta<NButton.TProps>;
export default meta;
export declare const Default: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NButton.TProps>;
export declare const WithIcon: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NButton.TProps>;
export declare const WithLoading: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NButton.TProps>;
export declare const WithDisabled: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NButton.TProps>;
export declare const AsBlock: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NButton.TProps>;
export declare const WithIconAtEnd: import('@storybook/csf').AnnotatedStoryFn<import('@storybook/react').ReactRenderer, NButton.TProps>;
export declare const ButtonDefaultBadge: StoryFn<NButton.TProps>;
export declare const ButtonGhostBadge: StoryFn<NButton.TProps>;
export declare const ButtonDangerBadge: StoryFn<NButton.TProps>;
export declare const ButtonIconOnly: StoryFn<NButton.TProps>;
export declare const ButtonDisabledTooltip: StoryFn<NButton.TProps>;
